### ISSUE TITLE
Feature Request: Speed up Alias Search / Implement Tag Search

### ISSUE THREAD

**Issue by chrisgrieser** [chrisgrieser/shimmering-obsidian#10]
I would like to improve the speed of Alias Search and implement a Search for Tags, but I lack the coding knowledge to implement this in a sufficiently efficient way – Alias search is already pretty slow, as the YAML-Header of every note has to be scanned.

I thought about building some sort of index/cache for that, but I am unsure how to properly keep such an index up to date – any Alias/Tag Search should reflect the current aliases and tags after all. 

I only code in my leisure time while having a non-technical job, so learning how to do that takes a bit of time for me – so I'd very much welcome help / pull requests in that regard!

**Comment by nwehrle** [comment]
I would really like to have that feature, but consider it a bad idea to build a "shadow-index" on your own. Obsidian obviously already has this and is in the proper position to maintain this index. A 3rd party has to do it in the background, on search-time or on-demand unless the search API is open to plugin developers.

How about doing it "von hinten durch die Brust ins Auge" with the means you already have?
1) On Alfred command creates a shimmering-tags.md (has to be called from time-to-time)
2) On Alfred command searches within this single document

**Comment by chrisgrieser** [comment]
I agree, I would rather use the index already created by Obsidian. But it seems that that index, if it is stored locally somewhere, is not as easily accessible as other stuff. Like starred files, recent files etc. are all basically written in plain text into one of the files in `.obsidian` – with tags, this is not the case, it seems.

If anyone has some pointers how to use the Obsidian API (which I have no knowledge of), I'll happily take a look.

**Comment by nwehrle** [comment]
Did you analyze the content of ~/Library/Application Support/obsidian?

**Comment by nwehrle** [comment]
If I am using the chromium-dev-tools there is quite some interesting content below IndexedDB:
<img width="1098" alt="Screenshot 2021-09-02 at 16 36 27" src="https://user-images.githubusercontent.com/832234/131863385-a7971f9c-86f7-45df-bf31-3fa5e82b7e8a.png">
So my bet is, that the metadata is stored using: https://w3c.github.io/IndexedDB/

**Comment by chrisgrieser** [comment]
Well, I am not sure I have the time resources to learn database stuff, but I'll happily accept Pull Requests that add does get the tags out of that and add the code necessary for Alfred.

**Comment by chrisgrieser** [comment]
Hmm, looks like IndexDB [cannot be accessed from the outside](https://discord.com/channels/686053708261228577/840286264964022302/886293344953720913), making some sort of "shadow index" necessary to access tags of vault. 🙁

**Comment by chrisgrieser** [comment]
Okay, there might be hope at some point in the future:
> This works on Local Storage LevelDBs - support for IndexedDBs using the idb_cmp1 comparator is coming soon
https://github.com/mdawsonuk/LevelDBDumper

**Comment by nwehrle** [comment]
I am not sure what kind of implications the availability of a "from the outside" tool may have. I understand it mainly as a security feature to access the indexedDB only from the current browsing context.
For your usecase LevelDBDumper might be a valid short sight solution, but on the long run the discussion on discord seems to be the promising path: having an obsidian-plugin that opens up a communication channel to obsidian's inner workings.

**Comment by chrisgrieser** [comment]
true, but well, I'll take what I can get. (so long there are no security issues, of course)

**Comment by chrisgrieser** [comment]
I think I am getting closer: [according to @koala](https://discord.com/channels/686053708261228577/886892352088731688/886940291435724802), a bridge plugin would only need to run two commands
```js
JSON.stringify(app.metadataCache.metadataCache)
JSON.stringify(app.metadataCache.fileCache)
```
it seems that the Readwise & the Jupyter Notebook plugin write files to their plugin folder. Combine those two, and the bridge plugin would be done.

And according to t[his info on plugin development](https://forum.obsidian.md/t/how-to-get-started-with-developing-a-custom-plugin/8157/7?u=pseudometa), one could actually skip all that TypeScript/NPM stuff and write in plain javascript. Now only to find out how...

**Comment by chrisgrieser** [comment]
https://github.com/kometenstaub/bridge

:)

**Comment by chrisgrieser** [comment]
done, will be part of the 2.0 release.
