### ISSUE TITLE
[Bug]: cannot search folders (neither starred and recent items)

### ISSUE THREAD

**Issue by sk365** [chrisgrieser/shimmering-obsidian#103]
### Bug Description

Typing 'o foo folder' does not yield results even if folder foo exists. 'o foo' does not yield results either. 
Same behaviour with 'o bar starred' and 'o bar recent'
Else quick switcher search works fine. 
Please help. 

### To Reproduce

see above. 

### Debugging Log

```Text
16:37:30.602] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[16:37:34.480] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[16:37:34.487] STDERR: Shimmering Obsidian[Script Filter] excluded files: undefined
[16:37:34.489] Shimmering Obsidian[Script Filter] {"items":[{"title":"_Task List","match":" Task List _Task List filename name title","subtitle":"▸ public_notes","arg":"public_notes/_Task List.md","quicklookurl":"/Users/stefan/Obsidian_Local/public_notes/_Task List.md","type":"file:skipcheck","uid":"public_notes/_Task List.md","icon":{"path":"icons/note.png"},"mods":
```

### Workflow Configuration 1

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>h_lvl_ignore</key>
	<string>h1 h2 h3 h4 h5 h6</string>
	<key>ocr_languages</key>
	<string>eng+deu</string>
</dict>
</plist>

### Workflow Configuration 2

<img width="1440" alt="Bildschirm­foto 2022-10-27 um 16 41 33" src="https://user-images.githubusercontent.com/47894034/198319558-1ea8d95a-fc17-405b-bfa2-9c093ed8da65.png">

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
Metadata String Length: 5834893
-------------------------------
WORKSPACE DATA
'workspace' exists
'workspace.json' exists
-------------------------------
INSTALLED VERSION
macOS: 13.0
Alfred: 5.0.3
---
Obsidian: 1.0.3
This Workflow: 3.1.3
Advanced URI Plugin: 1.17.0
Metadata Extractor: 1.0.2
-------------------------------
LATEST VERSION
Obsidian: 1.0.3 (Insider: 1.0.3)
This Workflow: 3.1.3
Advanced URI Plugin: 1.28.2
Metadata Extractor: 1.0.2
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/stefan/Obsidian_Local
Vault Name (encoded): Obsidian_Local
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o…` main search does not work, I have tried rerunning `osetup` and it still does not work.
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment]
should most likely be fixed with the latest release 3.3.1. If not please leave a comment and I'll re-open.
