### ISSUE TITLE
Feature Request: Open Note in New Tab by Default

### ISSUE THREAD

**Issue by adamsiem** [chrisgrieser/shimmering-obsidian#106]
### Feature Requested

When searching in Alfred to find a note with: `o <notecontents>` and selecting an item to open, it opens in the existing/last used Obsidian tab.

The request is to open the selected note in a new tab in Obsidian by default. Additionally, adding an option to select this in the configuration would be helpful.

### Checklist

- [X] Feature Requests regarding daily notes unfortunately will not be implemented, since I do not use daily notes myself and there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
you can already open in a new tab by using `cmd+return` instead of `return`. [See the docs on searching notes.](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Alfred-based%20Quick%20Switcher.md#search-for-notes)
