### ISSUE TITLE
Feature Request: Search Canvas file

### ISSUE THREAD

**Issue by Missionary2112** [chrisgrieser/shimmering-obsidian#107]
### Feature Requested

It would be great to search Canvas file. 

### Checklist

- [X] Feature Requests regarding daily notes unfortunately will not be implemented, since I do not use daily notes myself and there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
It already does; if you update to the latest version of the workflow and the latest version of the metadata extractor plugin 🙂
