### ISSUE TITLE
Feature Request: Copy Filename or paste note as a wiki link

### ISSUE THREAD

**Issue by splnkr** [chrisgrieser/shimmering-obsidian#109]
### Feature Requested

Hello,

I would like to have the option to copy the file name. When using other programs (pdf annotation) I search via the plugin for potential links and paste the filename with Wiki-Links to refer to an obsidian note. My notes have zettel-id prefixes. Right now I copy via cmd+c, but I also get the file path within Obsidian. 

Better for this specific workflow would be the feature to paste the found note as a wiki link in the opened application.

Kind regards,
splnkr

### Checklist

- [X] Feature Requests regarding daily notes unfortunately will not be implemented, since I do not use daily notes myself and there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
Why would you want to have the wikilink though? The wikilink is only valid inside Obsidian, so it will be of no use for writing in outside apps. And inside Obsidian, you already get suggestions for wikilinks in the editor.

Maybe I am not following, but I do not see the use case for this?

**Comment by kenanmike** [comment]
> 
![image](https://user-images.githubusercontent.com/85374001/222777779-b1fd0765-6e1b-48f9-9ca3-7c40e34d7b40.png)
![image](https://user-images.githubusercontent.com/85374001/222777788-09ff9907-dac3-4537-b42b-2a88fe90e5f0.png)

Hi Chris, I'm not @splnkr but just to throw in why it'd also be very useful for me:
Let's say I'm annotating a journal article that in one bit nicely summarises Leibniz's thought. I hit my Shimmering shortcut and am able to paste my Leibniz wikilink immediately into my annotation on the article.

When I export my annotations to Obsidian, my comment in the literature note already links directly to the Leibniz page I have. That way without needing to have done any editing or processing, when I open the Leibniz page, through Strange New Worlds I already have linked into that a great summary of what he wrote from what I read. Just from exporting my pdf annotations That way topic and people notes I have get populated effortlessly simply as I go through my normal reading of journal articles, and same for all the annotating on Kindle Books, podcasts, webpages I do via Readwise.

**Comment by splnkr** [comment]
Hello,
yes the explanation from @kenanmike is the reason why I requested that feature. Also WikiLinks are not only supported in Obsidian. There exist a variety of programs now.

**Comment by kenanmike** [comment]
I've worked out a hacky way of getting the result we want by editing the 'External Script' of the 'Copy Markdown Link' :
![image](https://user-images.githubusercontent.com/85374001/222797936-a750ad69-90bf-46b7-9fe9-c37f5dacf50d.png)
Then click open file to edit:
![image](https://user-images.githubusercontent.com/85374001/222798003-eb57980d-1e91-438f-bf50-45d2636d1eb7.png)

And then edit the last line look like this:
![image](https://user-images.githubusercontent.com/85374001/222799100-55697321-7af2-48ae-aaca-657035ffd7e1.png)

Finally, all you need to do is add a utilities function of 'replace' between 'external script' and 'copy to clipboard' like this:
![image](https://user-images.githubusercontent.com/85374001/222799238-e5a69293-1a5c-42a3-a807-4691e44f7bac.png)
And fill in .md in the first box and leave everything else:
![image](https://user-images.githubusercontent.com/85374001/222799255-56147d38-6026-4ce5-908d-cb419aa932dd.png)

And now it will copy the WikiLink of your file!

**Comment by splnkr** [comment]
Nice @kenanmike. Thank you very much for the customisation. It works really well!

**Comment by chrisgrieser** [comment]
I see. I added an option to copy a wikilink instead of a markdown link when using `ctrl+return`.

![CleanShot 2023-03-03 at 20 49 19](https://user-images.githubusercontent.com/73286100/222813361-07a70ea7-a463-4585-bf9b-409e8a7638fb.png)


(Since there currently is no update mechanism due to the wait for the Alfred Gallery, you have to update manually to 3.7.0: https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/3.7.0 )
