### ISSUE TITLE
Support linking and moving the screenshot picture when using the OCR command

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/shimmering-obsidian#11]
When using the OCR command, is it possible to link the screenshot picture into the screenshot note, e.g., at the beginning of the note?

- The screenshot picture would be moved to a selected folder in an Obsidian vault.
- The user may set the link format to be either the Obsidian format `![[Screenshot.png]]` or the Markdown format `![](Screenshot.png)`.

**Comment by wenlzhang** [comment]
Another related request is that it might also be useful to not perform OCR on the screenshot, but just move the screenshot picture to the desired location and link it to the currently active note.

**Comment by chrisgrieser** [comment]
well, it wouldn't be the OCR command anymore, but rather a new command for saving screenshots automatically to a note. Nevertheless, an interesting idea, I'll put it on the to do list.

**Comment by wenlzhang** [comment]
Just to clarify. In the first comment, I meant performing OCR and linking/moving the screenshot picture at the same time. In the second comment, I meant only linking/moving the screenshot picture (without performing OCR).

**Comment by chrisgrieser** [comment]
With version 2.7, I expanded the screenshot features, now you have one hotkey for taking an OCR screenshot and one hotkey for taking a normal (image) screenshot: https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Screenshot%20Features.md

I didn't implement combining both into one command as you suggested, though, as the OCR quality suffers when you include much more than text in the screenshot, so in practice, it is probably better to take an OCR screenshot and than an image screenshot to include any pictures.

However, I also added an option to *not* open Obsidian after taking a screenshot with either, so you can take OCR and image screenshots in quick succession, which should alleviate the issue!
