### ISSUE TITLE
Appending text to a note does not work ($.getenv is not a function)

### ISSUE THREAD

**Issue by DavinHarb** [chrisgrieser/shimmering-obsidian#111]
### Change Requested

Appending text to a file using `o` + `fn + ⏎ ` does not work for me.

When trying the debugger displays this error message:
`[00:09:19.776] ERROR: Shimmering Obsidian[Run Script] /Users/davin/Documents/Alfred Preferences/Alfred.alfredpreferences/workflows/user.workflow.DDFBF08C-7DF9-4A2E-B7D8-71EBB6FC6DCF/append-to-file.js: execution error: Error: TypeError: $.getenv is not a function. (In '$.getenv("append_prefix")', '$.getenv' is undefined) (-2700)`

I am using macOS Ventura Version 13.1 (22C65), Chip Apple M1 Pro, Alfred 5 & the latest version of shimmering-obsidian: 3.5.2.

Do you have any clue, how I can fix the error?

### Link to the relevant section of the documentation

https://github.com/chrisgrieser/shimmering-obsidian/blob/3.5.2/docs/Alfred-based%20Quick%20Switcher.md

**Comment by chrisgrieser** [comment]
thx, fixed in the latest release.

btw, next time please use the bug report form if you want to report bugs and not the form for documentation improvements.

**Comment by chrisgrieser** [comment]
cannot reproduce, it works on my end. Could you open a bug report form?

the bug report form requests various kinds of information I need to look into it.

**Comment by mike4263** [comment]
The impacted file is scripts/absolute-to-relative-path.js .  I am trying to debug the OCR Text into Obsidian workflow.  I'll open a bug report.
