### ISSUE TITLE
[Bug]: 'ON' does not create new note

### ISSUE THREAD

**Issue by lrzuniga** [chrisgrieser/shimmering-obsidian#115]
### Bug Description

keyword 'on' does not create a new note in obsidian

### Debugging Log

```Text
[19:43:15.007] Logging Started...
[19:43:18.345] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[19:43:19.833] Shimmering Obsidian[Keyword] Processing complete
[19:43:19.837] Shimmering Obsidian[Keyword] Passing output 'TEST' to Conditional
[19:43:19.838] Shimmering Obsidian[Conditional] Processing complete
[19:43:19.839] Shimmering Obsidian[Conditional] Passing output 'TEST' to Run Script
[19:43:20.021] STDERR: Shimmering Obsidian[Run Script] URI: obsidian://advanced-uri?vault=[VAULT]&filepath=%2FTEST&mode=new&line=999999999999999&data=
[19:43:30.645] Logging Stopped.
```

### Workflow Configuration 1

<img width="1139" alt="2023-02-04_19-44-30" src="https://user-images.githubusercontent.com/5016961/216795682-0d1913b4-92fc-401c-bd75-e27bf157c19c.png">

### Workflow Configuration 2

<img width="939" alt="2023-02-04_19-45-48" src="https://user-images.githubusercontent.com/5016961/216795707-c3dbc2ee-7ced-4ccc-9e12-7ad7eb25109d.png">

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/[user]/[folder]/Obsidian/[vault]
.obsidian: exists
Metadata JSONs: 1/4
Not all metadata not found. Please run `osetup` and retry.
metadata.json String Length: 209486
-------------------------------
WORKSPACE DATA
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 13.2
Alfred: 5.0.6
-------------------------------
INSTALLED VERSION
Obsidian: 1.1.9
This Workflow: 3.6.2
Advanced URI Plugin: Advanced URI plugin not installed.
Metadata Extractor: Metadata Extractor plugin not installed.
-------------------------------
LATEST VERSION
Obsidian: 1.1.9 (Insider: 1.1.12)
This Workflow: 3.6.2
Advanced URI Plugin: 1.31.2
Metadata Extractor: 1.1.0
-------------------------------
```

### Make sure you have done the following

- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).
- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o…` main search does not work, I have tried rerunning `osetup` and it still does not work.
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment]
You have to install the required plugins for this würdigte to work; see the installation instructions in the readme.

**Comment by chrisgrieser** [comment]
(just in case: I found a bug that would prevent new note creation in some edge cases, which I have fixed in the latest release https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/3.6.5)
