### ISSUE TITLE
Feature Request: support multiple computers and a shared Alfred directory

### ISSUE THREAD

**Issue by jotka** [chrisgrieser/shimmering-obsidian#116]
### Feature Requested

I have Alfred and SO on multiple computers. I share the Alfred configuration directory using Syncthing, but I guess it would be the same if use iCloud.

The thing is, everytime I switch computers, I need to re-initialize the workflow with 'osetup', again and again. The paths are the same (the synced folder location in the system).

I mean, it makes this workflow unusable :-|

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
I use Alfred and Obsidian on multiple devices, too, and have no issue with it. could you elaborate what exactly the problem is?

**Comment by chrisgrieser** [comment]
on those different devices, is your Obsidian vault saved in different locations?

**Comment by chrisgrieser** [comment]
Then I don't see why this should not be working, and it sounds more like a bug to me. Could you please open a bug report? Reason being that the bug report form asks for various kinds of information I need to investigate into what's causing this.
