### ISSUE TITLE
[Bug]:  Problem with searching notes (o-search)

### ISSUE THREAD

**Issue by skhalymon** [chrisgrieser/shimmering-obsidian#117]
### Bug Description

When typing in "o", nothing shows up. Other types of searches (ot, os, or) and commands (ob, oc, ol) works though. The fallback search doesn't work either.

I have run osetup and oupdate multiple times, and I only have 1 vault. Both Metadata Extractor and the Advanced URI plugins, are installed, enabled, and up-to-date.

Seems to be same as https://github.com/chrisgrieser/shimmering-obsidian/issues/82

### Debugging Log

```Text
[21:47:54.805] Logging Started...
[21:47:57.617] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[21:47:57.868] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[21:47:57.874] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/s/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6BAFA234-9725-4A67-AD47-06B00AC10242/scripts/o_search.js: execution error: Error: TypeError: undefined is not an object (evaluating 'excludeFilter.length') (-2700)
```

### Workflow Configuration 1

They are setup by default

### Workflow Configuration 2

![image](https://user-images.githubusercontent.com/1163493/218861603-6f428728-0ac8-44e0-93de-f6f798df170b.png)

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/s/Documents/Obsidian/Collector
.obsidian: exists
Metadata JSONs: 4/4
metadata.json String Length: 1021533
-------------------------------
WORKSPACE DATA
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 13.2
Alfred: 5.0.6
-------------------------------
INSTALLED VERSION
Obsidian: 1.1.9
This Workflow: 3.6.3
Advanced URI Plugin: 1.32.0
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.1.9 (Insider: 1.1.13)
This Workflow: 3.6.3
Advanced URI Plugin: 1.32.0
Metadata Extractor: 1.1.0
-------------------------------
```

### Make sure you have done the following

- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).
- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o…` main search does not work, I have tried rerunning `osetup` and it still does not work.
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment]
Thanks, problem is fixed in the latest release
