### ISSUE TITLE
Feature Request: Allow workflow to find & open Canvas files

### ISSUE THREAD

**Issue by kenanmike** [chrisgrieser/shimmering-obsidian#118]
### Feature Requested

New(ish) Canvas files are of a different format than standard Obsidian markdown, so don't show up in the Shimmering Obsidian workflow. But they are quickly becoming one of the flagship features of Obsidian, so it would benefit almost all users to have those Canvas files accessible with this workflow.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
The Alfred workflow already supports searching for canvas files?
![CleanShot 2023-02-15 at 11 59 25](https://user-images.githubusercontent.com/73286100/219009325-24b9b600-70b0-47a0-b8f4-e1fa95901a9f.png)

**Comment by kenanmike** [comment]
Hmm when I search the name of the Canvas note (Dashboard) it
 doesn’t come up (Dashboard1 is a different normal MD note)

**Comment by chrisgrieser** [comment]
> Hmm when I search the name of the Canvas note (Dashboard) it
 doesn’t come up (Dashboard1 is a different normal MD note)

Try updating to the latest version of the metadata-extractor plugin and rerunning `osetup` afterwards. 

If you still cannot find canvas files then, that would be a bug. In that could you open a bug report? Reason being that the bug report form asks for various kinds of information I will need to investigate the issue then.
