### ISSUE TITLE
[Bug]: Canvas notes not coming up on search

### ISSUE THREAD

**Issue by kenanmike** [chrisgrieser/shimmering-obsidian#119]
### Bug Description

Canvas notes not coming up on search in this workflow

### To Reproduce

Activate the workflow, type name of the Canvas note (or 'Canvas') and the notes won't come up.
[Canvas issues with Shimmering Obsidian.txt](https://github.com/chrisgrieser/shimmering-obsidian/files/10743116/Canvas.issues.with.Shimmering.Obsidian.txt)

### Debugging Log

```Text
Attached above
```

### Workflow Configuration

![image](https://user-images.githubusercontent.com/85374001/219031850-62c7edc8-7de8-4fd5-8068-1db67638381c.png)
![image](https://user-images.githubusercontent.com/85374001/219031859-94a72faf-a25a-462e-b15e-301bdf4a3d47.png)

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 4/3
Metadata String Length: 2883650
-------------------------------
INSTALLED VERSION
macOS: 12.6.2
Alfred: 5.0.6

Obsidian: 1.1.9
This Workflow: 2.26.8
Advanced URI Plugin: 1.32.0
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.1.9 (Insider: 1.1.13)
This Workflow: 3.6.4
Advanced URI Plugin: 1.32.0
Metadata Extractor: 1.1.0
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment]
![CleanShot 2023-02-15 at 16 37 58](https://user-images.githubusercontent.com/73286100/219075627-116a58cd-d1e8-4250-bfc8-6f2ea95dc124.png)
![CleanShot 2023-02-15 at 16 38 20](https://user-images.githubusercontent.com/73286100/219075865-51bac22c-fb89-4469-9d95-44c1ea9c64eb.png)

You have an outdated version of this workflow from before there was the canvas feature in Obsidian 😉 

Update to the [latest version of this workflow](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/3.6.4). (you will have to **disable** workflow migration, and run `osetup` once again)

**Comment by kenanmike** [comment]
Sorry about this, I wasn't aware the updating process had changed and I was confused about how to update it (you mentioning to disable migration did the trick for me).

> ![CleanShot 2023-02-15 at 16 37 58](https://user-images.githubusercontent.com/73286100/219075627-116a58cd-d1e8-4250-bfc8-6f2ea95dc124.png) ![CleanShot 2023-02-15 at 16 38 20](https://user-images.githubusercontent.com/73286100/219075865-51bac22c-fb89-4469-9d95-44c1ea9c64eb.png)
> 
> You have an outdated version of this workflow from before there was the canvas feature in Obsidian 😉
> 
> Update to the [latest version of this workflow](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/3.6.4). (you will have to **disable** workflow migration, and run `osetup` once again)
