### ISSUE TITLE
[Bug]: Fallback search not working

### ISSUE THREAD

**Issue by Hamzablm** [chrisgrieser/shimmering-obsidian#121]
### Bug Description

I can't use fallback search on alfred. When I try to invoke the search using `o` and type `random_search` and I hit enter, it doesn't do anything.

### Debugging Log

```Text
[11:46:52.604 PM] Shimmering Obsidian[Fallback Search] Processing complete
[11:46:52.661 PM] Shimmering Obsidian[Fallback Search] Passing output 'o reddit' to Script Filter
[11:46:52.662 PM] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[11:46:52.874 PM] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[11:46:52.883 PM] STDERR: Shimmering Obsidian[Script Filter] excludeFilter: undefined
recentFiles length: 30
canvasArray length: 0
starredFiles length: 0
superIconList length: 0
[11:46:52.884 PM] Shimmering Obsidian[Script Filter] {"items":[{....
```

### Workflow Configuration

<img width="552" alt="image" src="https://user-images.githubusercontent.com/32052228/221706208-806ca4f7-9bbc-49cb-8981-89f3bcdffd95.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/32052228/221706309-c774a18c-d8cc-4ae3-b92c-e1e64e81541d.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/32052228/221706368-a1c4deef-b9b2-4aa9-88ea-ef665cb57e5e.png">

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/hamzabelmellouki/Documents/second_brain
.obsidian: exists
Metadata JSONs: 4/4
metadata.json String Length: 64037
-------------------------------
WORKSPACE DATA
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 13.1
Alfred: 5.0.6
-------------------------------
INSTALLED VERSION
Obsidian: 1.1.15
This Workflow: 3.6.5
Advanced URI Plugin: 1.33.0
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.1.15 (Insider: 1.1.15)
This Workflow: 3.6.5
Advanced URI Plugin: 1.33.0
Metadata Extractor: 1.1.0
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment]
From your debugging log, I suspect you are misunderstanding how the fallback search is supposed to work. 

Given you have a note named "reddit", you can find it via `o reddit`, or you can find it by typing `reddit` and then select the fallback search, which will then also show the reddit note.

If you search for `o foobar` and the note does not exist, selecting the fallback search also will not show anything, does nothing else than running `o foobar` again

**Comment by Hamzablm** [comment]
I see, I thought it would do a search like so :
<img width="152" alt="image" src="https://user-images.githubusercontent.com/32052228/222964780-d59b497c-4c29-48d6-8877-485cc1fd74bb.png">

How can I search for text inside the whole vault?

**Comment by chrisgrieser** [comment]
You don't. A full search through the vault would require indexing the vault, which an external app cannot do easily. There are plugins like omnisearch who do that job already better anyway
