### ISSUE TITLE
Feature Request: Partial Search for Filename

### ISSUE THREAD

**Issue by Unrealluver** [chrisgrieser/shimmering-obsidian#123]
### Feature Requested

Greetings,

Thank you for your great tools! It truly advances my effectiveness on obsidian-based workflow! 

(Because the version of my obsidian is 0.14.6 and the latest version of shimmering-obsidian could not work for me, I choose the v2.27.7 shimmering-obsidian from the released history.)

But I face a problem in that I could not apply a partial search for the filename. For example, the filename is '@Yang2022TeViT', but when I typed 'o TeViT', I could not get the search result directing to the file mentioned before. Moreover, I must type 'o @yang' to get the links to that file. 

However, the H1 head of '@Yang2022TeViT' is 'Temporally Efficient Vision Transformer for Video Instance Segmentation'. I noticed that I could get the file link by 'o for Video Instance S'. 

This kind of partial search for H1 head is very useful and so cooooooooool! And I wonder if I could use the partial search for the filename?

### Relevant Screenshot

<img width="577" alt="image" src="https://user-images.githubusercontent.com/27504120/229397808-af4318e2-1ead-4144-99d2-f5feaf4d3083.png">

![image](https://user-images.githubusercontent.com/27504120/229397857-5fc9d028-f520-4730-a90e-001cf6dc6b28.png)

![image](https://user-images.githubusercontent.com/27504120/229397899-eaf40140-8ab9-4452-9338-a279db1c496d.png)

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Ah haven't thought about people having CamelCase Notes. Alfred by default matches words, so the H1 was matched since it was space-delimited, which your note title were not.

While truely fuzzy or partial matching isn't easily possible with Alfred, it is possible to match by CamelCase, which I have just added now.

Download the latest release (3.8.2) and it should work :)

**Comment by Unrealluver** [comment]
Thanks, I will try that version latter again.
