### ISSUE TITLE
[Bug]: 3.9.2 is broken due to missing Info.plist

### ISSUE THREAD

**Issue by vitorgalvao** [chrisgrieser/shimmering-obsidian#128]
### Bug Description

Version 3.9.2 cannot be imported. Looking at the contents, both the `Changelog.md` and `info.plist` were removed. No harm on the former, but the absence of the latter breaks the workflow entirely.

### Relevant Screenshot

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1699443/233665671-3ac9d1aa-5589-42c6-83ea-d028db4b58e9.png">

### To Reproduce

1. Download 3.9.2 from the releases.
2. Try to install it.

### Debugging Log

```Text
N/A
```

### Workflow Configuration

N/A

### Version & System Information

```Text
N/A
```

### Last working version

3.9.1

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment]
oh thx, I forgot to unignore the file in my release script 🙈
fixed with 3.9.3

**Comment by vitorgalvao** [comment]
The `info-original.plist` is now included too. Intentional?

**Comment by chrisgrieser** [comment]
fixed
