### ISSUE TITLE
Feature request: Support selecting file types when backing up the vault

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/shimmering-obsidian#13]
Is it possible to select file types to be backed up? For instance, one may only want to back up Markdown notes but not certain types of attachments.

**Comment by chrisgrieser** [comment]
that's a nice idea. However, I'll have to think about how exactly you will be able to exclude things, since people will have very different backup requests.

I'll put it on the to-do-list for now!

**Comment by chrisgrieser** [comment]
I considered implementing this, but I noticed that offering enough customizability that other users would also profit from this would take a lot of time. However, using the [Obsidian Git plugin](https://github.com/denolehov/obsidian-git), you can use a `.gitignore` file to get fine-grained control over what you want to backup. Probably, the Git Plugin is the better backup solution for you?

**Comment by wenlzhang** [comment]
> Probably, the Git Plugin is the better backup solution for you?

Thanks for the suggestion. I may look into this.
