### ISSUE TITLE
[Bug]: Help search doesn't work

### ISSUE THREAD

**Issue by Sinled** [chrisgrieser/shimmering-obsidian#132]
### Bug Description

Hi
for some reason `oh` command returns empty result

when you type `oh` icon with search text briefly appears and then alfred fallbacks to default search

Debug log has non printing characters, i've attached screenshot

[log.txt](https://github.com/chrisgrieser/shimmering-obsidian/files/11584946/log.txt)

### Relevant Screenshot

<img width="1297" alt="Screenshot 2023-05-28 at 18 14 36" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/1402135/0443f131-b79d-4869-b2e6-c58f00a4a077">

### To Reproduce

type `oh`

### Debugging Log

```Text
Attached file in description
```

### Workflow Configuration

<img width="519" alt="Screenshot 2023-05-28 at 18 07 49" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/1402135/f13a261e-73d0-48ac-8d3b-e8c208a407ba">
<img width="511" alt="Screenshot 2023-05-28 at 18 07 43" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/1402135/7dafc6ad-d152-4068-bace-d57bb1918ad2">
<img width="513" alt="Screenshot 2023-05-28 at 18 07 33" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/1402135/3cca3ec6-afee-4892-b79b-aa8308ee423f">

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/Library/Mobile Documents/iCloud~md~obsidian/Documents/main
.obsidian: exists
Metadata JSONs: 4/4
metadata.json String Length: 246920
-------------------------------
WORKSPACE DATA
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 13.3.1
Alfred: 5.1
-------------------------------
INSTALLED VERSION
Obsidian: 1.3.4
This Workflow: 3.9.4
Advanced URI Plugin: 1.35.0
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.3.4 (Insider: 1.3.4)
This Workflow: 3.9.4
Advanced URI Plugin: 1.35.0
Metadata Extractor: 1.1.0
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment]
Could you use `oupdate` and run `Re-Index Documentation Search`, and then try `oh` again?

**Comment by Sinled** [comment]
Sadly result is the same,  some characters appended before json: `]697;OSCLock=]697;PreExec`

**Comment by Sinled** [comment]
I've remembered that i had similir problem in other workflow when `zsh` was used to run script

just changed it to `bash` and it works fine now.

<img width="820" alt="Screenshot 2023-05-28 at 19 02 01" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/1402135/80e62ada-d2f6-436c-8874-b317273e9997">

**Comment by chrisgrieser** [comment]
huh, that is really weird, but good to know 🤔 
will be added to the next release
