### ISSUE TITLE
[Bug?]: Alfred gallery still has 3.9.4 version of the workflow

### ISSUE THREAD

**Issue by danieltomasz** [chrisgrieser/shimmering-obsidian#136]
### Bug Description

I dont know if there is specific issue of update time betweeen github updates and Alfred gallery updates, but Alfred Gallery has the 3.9.4 as the latest and downgrade the github installed version.

Maybe it is normal to take some time, or the issue is on the alfred side but I am reporting it here anyway

### Debugging Log

```Text
ALfred 5.1.2 prelease 
MacOS 13.4
```

### Workflow Configuration

Dont think it matters

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/daniel/PhD/Projects/ephys-poirot-analysis/thesis
.obsidian: exists
Metadata JSONs: 4/4
metadata.json String Length: 164823
-------------------------------
WORKSPACE DATA
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 13.4.1
Alfred: 5.1.2
-------------------------------
INSTALLED VERSION
Obsidian: 1.3.7
This Workflow: 3.9.4
Advanced URI Plugin: 1.36.3
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.3.5 (Insider: 1.3.7)
This Workflow: 3.10.3
Advanced URI Plugin: 1.36.3
Metadata Extractor: 1.1.0
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).

**Comment by chrisgrieser** [comment]
Hi,

yes, I noticed this as well. It's either a lag on GitHub's side or on Alfred's side. 

If it's still not up to date tomorrow, you should report the issue in the Alfred forum. 

Unfortunately, there is nothing I can do about it on my end 😕
