### ISSUE TITLE
[Bug]: New Note not created by workflow (on)

### ISSUE THREAD

**Issue by onedrop2000** [chrisgrieser/shimmering-obsidian#137]
### Bug Description

Hi, 
I installed the Plugins and the Workflow, but its not creating a new note when I write "on test note" .. 
I use the latest Alfred 5 version + Obsidian Version 1.3.5

The main search is working perfectly.

Any Ideas what I missed?

Thanks a lot for you effort!!

Cheers :)

### To Reproduce

1. Open Alfred
2. Type on test note
3. Obisidian opens 
4. nothing happens (no new note is beeing created

### Debugging Log

```Text
[11:20:23.624] ERROR: Shimmering Obsidian[Run Script] /Users/jojo/Library/Mobile Documents/com~apple~CloudDocs/Apps/Alfred App/Alfred.alfredpreferences/workflows/user.workflow.A75CFD8B-8933-4A99-B3B2-B34ED80F2888/scripts/new-note.js: execution error: Error: Error: exception raised by object: *** +[NSString stringWithUTF8String:]: NULL cString (-2700)
```

### Workflow Configuration

Default

### Version & System Information

```Text
Alfred 5 version
Obsidian Version 1.3.5
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).

**Comment by chrisgrieser** [comment]
thanks, is fixed with release 3.11.1
