### ISSUE TITLE
Feature Request: Disable Emojis in search fields

### ISSUE THREAD

**Issue by notpoweruser1** [chrisgrieser/shimmering-obsidian#139]
### Feature Requested

Hi, I'm a VoiceOver user (screen reader) and wonder if it's possible to disable emojis in search fields. Such as 🔖, 🕑 etc. Since those Emojis came before the note title, the screen reader reads those first. It can be time-consuming when you try to navigate a chunk of notes.

I tried to remove those Emojis manually from the code, but after updating the workflow to the newer version, those Emojis came back.

Would it be possible for you to implement a toggle in the configuration of workflow to enable/disable showing of Emoji while searching for the notes?

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Good point, haven't thought about them being an accessibility issue there.

I just released [version 3.12.7](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/3.12.7), which introduces a setting to disable the addition of emojis in most places. 

Please let me know if I missed some emojis somewhere, and I'll make the new setting apply there as well.
