### ISSUE TITLE
[Bug]: Create new Note feature not working

### ISSUE THREAD

**Issue by edoski** [chrisgrieser/shimmering-obsidian#140]
### Bug Description

The Create new Note feature, when inside of a subfolder from search, isn't working for me as the new note is never created.

Some potentially useful information to consider is that the vault on which this isn't working is also synced through Obsidian Sync, but I'm the owner of the vault and am on the same machine on which it was created.

I mention this because I created a local test vault with a test folder inside of it, and oddly enough on this vault the create new note feature worked.

I attach a zip containing the logs for the working and malfunctioning vault here as .rtf files:
[logs.zip](https://github.com/chrisgrieser/shimmering-obsidian/files/12193278/logs.zip)

(Note that in the logMalfunctioning.rtf file I edited out the {"items":} section for privacy reasons).

### Relevant Screenshot

<img width="1512" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/622e171e-f2d0-4c45-9e70-defcdaa02eea">

### To Reproduce

1. o <folder_name>
2. Select folder
3. Select "Create new Note"

### Debugging Log

```Text
See Bug description.
```

### Workflow Configuration

<img width="506" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/0a6d22c7-e1cf-4c75-952b-163dd50b4cc1">

<img width="503" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/6597a6fe-85e7-410f-a8bd-98bb0cc029e9">

<img width="501" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/45b94a10-02b8-4164-b271-e83a7ef000b3">

<img width="502" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/7151efd5-dff8-4545-bdb1-bd28aa2e2816">

<img width="502" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/c66f5e89-a4c7-4e68-abe3-373e48a321e5">

### Version & System Information

```Text
oinfo command not working for me.

- macOS: 14.0 Beta (23A5286i)
- Alfred: v5.1.1 [2138]
- Obsidian: v1.3.5 
- Workflow: v3.12.6
- Metadata Extractor: v1.1.0
- Advanced URI: 1.36.4

- allExceptMD.json, tags.json, metadata.json: All in folder and all non-empty.
- {vault-path}/.obsidian/workspace.json: Exists.

- Environment Variables: In Relevant Screenshot section.
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).

**Comment by chrisgrieser** [comment]
alright, found the likely issue, should be fixed now

**Comment by edoski** [comment]
can confirm it works, many thanks!
