### ISSUE TITLE
[Bug]: Template not working when creating a new note

### ISSUE THREAD

**Issue by edoski** [chrisgrieser/shimmering-obsidian#141]
### Bug Description

After having set in the configuration the note path to my template of choice, I noticed that when using the command `on <new_note_title>` it would create the new note, import the template, but wouldn't swap text segments like {{date:YYYYMMDD}} with the actual date itself.

To note, it would work with {{title}} in the title section of the note, but wouldn't for any that were in the note body like the above mentioned {{date:YYYYMMDD}}.

### Relevant Screenshot

<img width="1512" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/2b20f6ef-3134-4f5d-9ac1-92d8082ed254">

### Debugging Log

```Text
[17:56:39.445] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[17:56:45.275] Shimmering Obsidian[Keyword] Processing complete
[17:56:45.283] Shimmering Obsidian[Keyword] Passing output 'test note' to Run Script
[17:56:45.562] Shimmering Obsidian[Run Script] Processing complete
[17:56:45.565] Shimmering Obsidian[Run Script] Passing output '01 Fleeting Notes/Test note.md
' to Call External Trigger
[17:56:45.566] Shimmering Obsidian[External] Processing complete
[17:56:45.566] Shimmering Obsidian[External] Passing output '01 Fleeting Notes/Test note.md
' to Run Script
[17:56:45.854] Shimmering Obsidian[Run Script] Processing complete
[17:56:45.859] Shimmering Obsidian[Run Script] Passing output '' to Hide Alfred
[17:57:04.869] Logging Stopped.
```

### Workflow Configuration

<img width="1512" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/aaea00c0-b08a-454f-8b44-2389adc5a1da">

<img width="1512" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/cc399799-2bda-40bf-a42b-d8d68fc2f165">

<img width="1512" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/74e59eff-8177-40ef-9c8a-cfdbd1cf8e3e">

<img width="515" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/87473803/7d1f847d-2fbc-4aa7-b6ea-fe603cf31d8c">

### Version & System Information

```Text
(oinfo command not working)

- macOS: 14.0 Beta (23A5286i)
- Alfred: v5.1.1 [2138]
- Obsidian: v1.3.7
- Workflow: v3.12.8
- Metadata Extractor: v1.1.0
- Advanced URI: 1.36.5

- allExceptMD.json, tags.json, metadata.json: All in folder and all non-empty.
- {vault-path}/.obsidian/workspace.json: Exists.

- Environment Variables: In Relevant Screenshot section.
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).

**Comment by chrisgrieser** [comment]
That's not a bug, that's simply not a feature this workflow has implemented.

I see little value in implementing templating functionality when there are Obsidian plugins that can already do that.

So to get things like date insertion, please use a plugin like [Templater](https://obsidian.md/plugins?id=templater-obsidian)

**Comment by edoski** [comment]
Ahh I see, that makes sense, thanks for the clarification!
