### ISSUE TITLE
[Bug]: Unable to run task! error message

### ISSUE THREAD

**Issue by macmeister** [chrisgrieser/shimmering-obsidian#143]
### Bug Description

This is definitely related to Dropbox syncing workflows, however I'm not sure if it can be cured. With a little research with other scripts it might be easily curable and I wanted to let @chrisgrieser know just in case. Hopefully this is the right place.

After syncing workflows, it will continue to work locally on the original Mac, but when I get on the other one, I get the attached error when running it with the command oo anyway.
![Image 2023-08-10 at 10 28 15 PM](https://github.com/chrisgrieser/shimmering-obsidian/assets/3847742/ab0bf0c6-f558-44dd-895c-93dfc0e89b65)

I'm hoping maybe one of these posts will allow some insight or suggestions for a possible workaround?
https://github.com/ShogunPanda/alfred-chrome/issues/5
Could it be as easy as adding this somewhere?
#!/bin/bash

I found the above through this as well:
https://www.alfredforum.com/topic/19902-unable-to-run-external-script-from-workfolder-couldnt-posix_spawn-error-8/

### To Reproduce

1. Place Alfred Prefs folder (and workflows) in a Dropbox folder synced between 2 Macs. 
2. Alfred->Advanced Settings, select this preference folder on each machine.
3. Tried restarting computer, both Alfred and Obsidian with no solution. Works on 1st machine, but not the second synced one.

### Debugging Log

```Text
I'm not sure how relevant this is because I don't get the error when in this mode (just noting happens) but maybe that's normal. I'm not too familiar with debugging...

[22:47:59.666] Logging Started...
[22:48:04.762] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
```

### Workflow Configuration

These same settings work on the original machine, I even reviewed and resaved them on the synced machine with same error. Could be just a dropbox limitation, however other workflows appear to be working fine.
<img width="1496" alt="Screenshot 2023-08-10 at 10 53 07 PM" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/3847742/7815b5f1-9e83-499b-ab85-152549cd3c0a">
<img width="1496" alt="Screenshot 2023-08-10 at 10 53 25 PM" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/3847742/f0fb46ec-88ed-40bc-ae0f-6d8ac7799e8a">
<img width="1496" alt="Screenshot 2023-08-10 at 10 53 22 PM" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/3847742/62d4ebf0-4cdc-45d6-8a70-f7bf31e0b5f6">
<img width="1496" alt="Screenshot 2023-08-10 at 10 53 17 PM" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/3847742/a94acc1b-1364-4576-a63f-28a7ce38d022">
<img width="1496" alt="Screenshot 2023-08-10 at 10 53 12 PM" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/3847742/21c72b52-ba84-4a44-bf29-587e4d27e5d4">

### Version & System Information

```Text
Mac OS 13.5
oinfo got the same error.
Alfred 5.1.2
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the documentation of the feature I am having problems with.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.
- [X] I have not renamed my Obsidian config folder, it's still `.obsidian` (About → Advanced → Override config folder).

**Comment by chrisgrieser** [comment]
Yeah, you are right, this should be a syncing issue. 

Uninstall the workflow, and then reinstall it. (Run osetup etc again) That should fix it. 

Also, you have to run osetup once on every device you are using the workflow on

**Comment by macmeister** [comment]
Thank you! Is syncing possible, or not at all with this workflow? I will try your suggestion on both machines, but not sure if it will let me (with the syncing). I can post results…

**Comment by chrisgrieser** [comment]
Syncing works just fine, I sync with 3 devices without any issues.

I assume that dropbox just got stuck with the sync somehow. Therefore, the wipe and clean re-install.

**Comment by macmeister** [comment]
Thank you for clarifying your success, Chris! Will keep trying. I removed and reinstalled plugins on both Macs, however the second Mac is always the problem. It now works on Mac 2, but not Mac 1 (since I started fresh on it this time). Maybe it's because it's a shared dropbox folder. Are you suggesting removing and re-installing Dropbox too? It is fairly fresh on both Macs.

**Comment by macmeister** [comment]
Allow full disk access for Dropbox may have fixed it. Will post accordingly. ;)

**Comment by macmeister** [comment]
This is apparently an ongoing issue likely with Dropbox file permissions and Alfred, and still unresolved with this workflow, including others. If I find a solution, I will post it here. And if someone has a solution, please share. I'm testing other workflows with similar functionality as a possible substitute. Thanks for any tips! At least I'm not the only one:
https://www.alfredforum.com/topic/19572-workflows-not-working-after-syncing-to-dropbox/
