### ISSUE TITLE
Option to exclude folders/subfolders from search

### ISSUE THREAD

**Issue by edoski** [chrisgrieser/shimmering-obsidian#145]
### Feature Requested

As the title suggests, I think being able to exclude from search certain folders and subfolders when using the `o <folder_name>` command could be useful to users of this workflow, as it would provide the power to filter out potentially unnecessary search results, thereby making it even quicker and easier to find relevant files and folders^^

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hi, you can already do so. Shimmering Obsidian respects the Excluded files setting of Obsidian, allowing you to ignore certain folders. 

https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Alfred-based%20Quick%20Switcher.md
