### ISSUE TITLE
Feature Request: Search and filter by Property

### ISSUE THREAD

**Issue by saeedesmaili** [chrisgrieser/shimmering-obsidian#146]
### Feature Requested

Obsidian recently introduced [Properties](https://help.obsidian.md/Editing+and+formatting/Properties). It would be great to have an option to filter the search with properties when using this Alfred workflow. For example, user can limit the search results to notes which their type is wiki.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hi, that would require some changes upstream, meaning the metadata-extractor plugin would have to expose that information for this workflow to be able to do use it.

Please open a respective request at the metadata extractor repo: https://github.com/kometenstaub/metadata-extractor

**Comment by saeedesmaili** [comment]
[They said it is already supported](https://github.com/kometenstaub/metadata-extractor/issues/22) (since the new properties feature is a UI on top of the yaml frontmatter).

**Comment by chrisgrieser** [comment]
Okay, I'll have a look when I have some more time

**Comment by Mugurell** [comment]
Bump to maybe reopen/reconsider this.
