### ISSUE TITLE
Feature Request: Intelligent Sorting for Search Results & More Specific Search for File Sections

### ISSUE THREAD

**Issue by PenguinDang** [chrisgrieser/shimmering-obsidian#147]
### Feature Requested

**1. Intelligent Sorting for Search Results:**
When I search using Alfred, I notice that the results aren't always as relevant as I'd like them to be. For instance, when I have multiple pages containing the term "python", some are web clippings with the word "python" in the title, while others are pages related to Python. Inside Obsidian, the first result is usually the file named "python.md", which is very convenient. However, when using this plugin, less relevant pages often appear at the top, with the actual "python.md" file appearing much later in the search results. It would be great if the plugin could prioritize search results based on recent access history or the relevance of the title.

**2. More Specific Search for File Sections:**
I often find myself needing to search for specific headings within a file. For a Python beginner like me, I might frequently search for the "dict" section under the H2 heading in the "python.md" file. However, simply searching for "dict" returns too many results. It would be useful if I could refine my search with queries like "python dict" or "python h2 dict" to precisely locate the "dict" section within the "python.md" file.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
re 1:
- The feature you are mainly discussing here is the prioritization of exact matches. That's something I'd like to have as well, but it is not possible as Alfred does not allow that kind of sorting. You would have to request such a feature at the [Alfred Forum](https://www.alfredforum.com/). (Feel free to your post here afterward, so others and me can upvote it.)
- "It would be great if the plugin could prioritize search results based on recent access history" prioritization based on recently selected results is already implemented, meaning results you recently selected in Alfred are already moved to the top. For notes that you have recently opened in Obsidian, there is also the `or` search for recent notes.

re 2:
- everything you suggest here has already been implemented in the workflow. However, there was a bug related to the heading search, which resulted in some headings being ignored under certain circumstances. I fixed the bug in version 4.0.5: https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.0.5/shimmering-obsidian.alfredworkflow

**Comment by chrisgrieser** [comment]
re 1:
I just improved the sorting so that files that have been opened in Obsidian, but not opened via this Alfred workflow, are also prioritized in the sorting

**Comment by PenguinDang** [comment]
Firstly, I'd like to express my gratitude for the improvements in version 4.1.0. I'm now able to search both file names and internal headings, which is fantastic. However, I've noticed that the plugin currently doesn't support simultaneous searches for aliases and internal headings. It would be a significant enhancement if this feature could be integrated. Thank you for your continued efforts!

**Comment by chrisgrieser** [comment]
> However, I've noticed that the plugin currently doesn't support simultaneous searches for aliases and internal headings.

That's working fine for me?

You could try `oupdate` to manually refresh the metadata, in case it is out of date, but it definitely searches headings, files and aliases simultaneously for me. In case it's not working, I'd suggest you open a bug report, since the form asks for various kinds of further information I'd need to further look into it

**Comment by PenguinDang** [comment]
I've reinstalled the Alfred workflow and the two Obsidian plugins, and ensure there's no issue with my original data export. When I input a file name, not only does it display the file, but it also automatically shows the headings within that file. I can then continue typing to refine my search by the heading. However, when I type in an alias, it only displays the file associated with that alias and does not show the headings within the file. Consequently, continuing to type in the heading after the alias yields no search results.
![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/115391259/d98fc664-f7b1-4376-afce-7e0efad53541)
![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/115391259/989c173d-4fe1-4ebd-9a2b-3cf41a98c8b5)
![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/115391259/bf419b5d-9ad1-4756-b7c5-f194412ee1c8)
![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/115391259/617d5870-afe6-4c10-9020-df6481758925)

**Comment by chrisgrieser** [comment]
> When I input a file name, not only does it display the file, but it also automatically shows the headings within that file. I can then continue typing to refine my search by the heading. However, when I type in an alias, it only displays the file associated with that alias and does not show the headings within the file.

that is actually somewhat intentional, since having the headings also match via alias would create a lot of noise and make it harder to find a specific note. While dong so has the benefit of allowing to use an alias and then continue filtering, that mostly covers a quite niche case, as opposed to the cost of increasing noise for all other searches as well. Unfortunately, there is no perfect solution, but I think the current implementation is the best compromise.
