### ISSUE TITLE
[Bug]: Browse Folder Is Empty

### ISSUE THREAD

**Issue by hwangy** [chrisgrieser/shimmering-obsidian#149]
### Bug Description

When searching "o Useful Tools" and I hit enter to browse the corresponding folder, "Search Obsidian Vault" briefly pops up under the main search bar, but then disappears. No results show up for notes within the Obsidian folder.

I noticed that `oinfo` reports: "Not all metadata not found. Please run `osetup` and retry. metadata.json String Length: 209662". However, I've tried running osetup multiple times, but this issue persists.

### Relevant Screenshot

![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/5905309/ba0753be-07a5-45a1-82a4-4323e950da32)

![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/5905309/fd524811-0d74-4121-9285-2a18485eecb8)

### To Reproduce

1. Open Alfred
2. Search for a folder "o <folder name>"
3. Hit enter (to browse)
4. Nothing shows up

### Debugging Log

```Text
[14:59:28.988] Shimmering Obsidian[Script Filter] Processing complete
[14:59:29.018] Shimmering Obsidian[Script Filter] Passing output 'Research/Useful Tools' to Call External Trigger
[14:59:29.019] Shimmering Obsidian[External] Processing complete
[14:59:29.020] Shimmering Obsidian[External] Passing output 'Research/Useful Tools' to Arg and Vars
[14:59:29.020] Shimmering Obsidian[Arg and Vars] Processing complete
[14:59:29.021] Shimmering Obsidian[Arg and Vars] Passing output 'Research/Useful Tools' to Arg and Vars
[14:59:29.022] Shimmering Obsidian[Arg and Vars] Processing complete
[14:59:29.022] Shimmering Obsidian[Arg and Vars] Passing output 'Research/Useful Tools' to Conditional
[14:59:29.022] Shimmering Obsidian[Conditional] Processing complete
[14:59:29.023] Shimmering Obsidian[Conditional] Passing output 'Research/Useful Tools' to Call External Trigger
[14:59:29.023] Shimmering Obsidian[Script Filter] Running directly with argument ''
[14:59:29.024] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[14:59:29.254] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
```

### Workflow Configuration

![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/5905309/4721029c-e19f-46c1-8ca9-819ddd24f4ea)

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/yeongwoohwang/Documents/Woo's Vault
config folder: exists
Metadata JSONs: 0/4
Not all metadata not found. Please run `osetup` and retry.
metadata.json String Length: 209662
-------------------------------
WORKSPACE DATA
'workspace' exists
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 13.0
Alfred: 5.1.2
-------------------------------
INSTALLED VERSION
Obsidian: 1.4.13
This Workflow: 4.1.0
Advanced URI Plugin: 1.38.1
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.4.13 (Insider: 1.4.13)
This Workflow: 4.1.0
Advanced URI Plugin: 1.38.1
Metadata Extractor: 1.1.0
-------------------------------
```

### Last working version

3.8.1

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the documentation of the feature I am having problems with.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.

**Comment by chrisgrieser** [comment]
1. This is quite puzzling to me, since without any metadata, the search should already fail to begin with. Can you paste the debugging log when pasting `osetup`?
2. A possible reason why nothing in that particular folder can be found is that there is either no note, or that you added the folder (or all its notes) to the excluded files in the Obsidian settings (Files and Links → Excluded Files)
3. Could you go to the folder `yourVaultPath/.obsidian/plugins/metadata-extractor` and list all files in that folder?

**Comment by hwangy** [comment]
This is the output of the debugger when running `osetup`

[07:13:20.374] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[07:13:20.512] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[07:13:21.895] Shimmering Obsidian[Keyword] Processing complete
[07:13:21.896] Shimmering Obsidian[Keyword] Passing output '' to Run Script
[07:13:22.640] Shimmering Obsidian[Run Script] Processing complete
[07:13:22.640] Shimmering Obsidian[Run Script] Passing output '' to Conditional
[07:13:22.641] Shimmering Obsidian[Conditional] Processing complete
[07:13:22.641] Shimmering Obsidian[Conditional] Passing output '' to Post Notification
[07:13:22.641] Shimmering Obsidian[Post Notification] Processing complete
[07:13:22.642] Shimmering Obsidian[Post Notification] Passing output '' to Play Sound

My excluded files is empty:
![image](https://github.com/chrisgrieser/shimmering-obsidian/assets/5905309/2aaa3bfb-cf44-4e49-9e0f-17c45afb4b04)

I have the following files in `metadata-extractor`
- allExceptMd.json
- main.js
- tags.json
- canvas.json
- manifest.json
- data.json
- metadata.json

If it's useful, I also see that in `allExceptMd.json`, the following lines are present,
``
{
      "name": "Useful Tools",
      "relativePath": "Research/Useful Tools"
    },
``

**Comment by hwangy** [comment]
Something interesting that I've noticed; the browsing seems to fail when a folder contains no other subfolders. If I create a folder within the folder I'm searching for, then it works! If I then _delete the folder_, it once again fails.

**Comment by chrisgrieser** [comment]
It seems that the metadata is correctly created, only the `oinfo` command for some reason is not able to correctly identify it. Weird.

> Something interesting that I've noticed; the browsing seems to fail when a folder contains no other subfolders. If I create a folder within the folder I'm searching for, then it works! If I then delete the folder, it once again fails.

That's a good find! I pushed an update which potentially fixes this issue. Could you download it and try again? https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.1.1/shimmering-obsidian.alfredworkflow

In case it fails, please share the debugging log for when it fails.

**Comment by hwangy** [comment]
That fixed it!! Thank you for the quick fix!

**Comment by Miaoyifei-mz** [comment]
Hello, when I updated to the latest version, this problem recurred.

-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/zhuangzhu/Library/Mobile Documents/iCloud~md~obsidian/Documents/Md 文档
config folder: exists
Metadata JSONs: 4/4
metadata.json String Length: 746257
-------------------------------
METADATA EXTRACTOR CONFIG
{"writingFrequency":"30","writeFilesOnLaunch":true}
-------------------------------
WORKSPACE DATA
'workspace' exists
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 14.2.1
Alfred: 5.5
-------------------------------
INSTALLED VERSION
Obsidian: 1.5.12
This Workflow: 4.4.2
Advanced URI Plugin: 1.40.0
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.5.12 (Insider: 1.5.12)
This Workflow: 4.4.2
Advanced URI Plugin: 1.40.1
Metadata Extractor: 1.1.0
-------------------------------

**Comment by Miaoyifei-mz** [comment]
@chrisgrieser

**Comment by Miaoyifei-mz** [comment]
@chrisgrieser Thank you for your quick reply!😄️,I just found out that it might be a problem with the latest version of Alfred (5.5), and when I went back to the previous version (5.1.4), the workflow worked well without folder problems. Let's see if Alfred has the same problem after another update🤔️.
