### ISSUE TITLE
Feature Request: Chinese Documentation

### ISSUE THREAD

**Issue by dangxiajishi** [chrisgrieser/shimmering-obsidian#151]
### Feature Requested

您好大神,我这两天一直配置您这个插件,一直配置不成功,能否出一份详细的中文版的配置说明呢?我是一个小白,特别想用这个插件,感恩!
/

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hi, the best I could do would be to use Google Translate, which you probably already tried yourself. 😕 

If anyone contributed a Chinese translation, I'll gladly add it, though.

You could also ask in the Chinese section of the Obsidian forum, or the Chinese channel of the Obsidian Discord server for some help?

**Comment by dangxiajishi** [comment]
ok，thank you。发自我的 iPhone在 2023年9月21日，19:53，pseudometa ***@***.***> 写道：﻿
Hi, the best I could do would be to use Google Translate, which you probably already tried yourself. 😕
If anyone contributed a Chinese translation, I'll gladly add it, though.
You could also ask in the Chinese section of the Obsidian forum, or the Chinese channel of the Obsidian Discord server for some help?
