### ISSUE TITLE
Feature Request: Quick vault switcher

### ISSUE THREAD

**Issue by Sinled** [chrisgrieser/shimmering-obsidian#152]
### Feature Requested

Follow up of this [discussion](https://github.com/chrisgrieser/shimmering-obsidian/discussions/150)

It would be nice to have ability to quickly switch vaults, or directly search in specific vault, without manually changing folder in workflow configuration.

It might be useful for people which have several often used vaults, e.g. work and personal.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by Sinled** [comment]
bump? as I understand it is still not a thing

**Comment by chrisgrieser** [comment]
The way Alfred currently works, this feature is currently not possible to implement, as Alfred does not allow for workflows to change its own settings file.

I created a feature request in the Alfred forum, which you can upvote to indicate interest for this to the Alfred devs: https://www.alfredforum.com/topic/22002-hot-reload-changes-to-prefsplist/

**Comment by chrisgrieser** [comment]
Nevermind, as explained by Andrew (Alfred dev), this can actually be achieved already. I added the ability to change the vault you want to control on the fly, using `shift+enter` in the `ov` search. (The `Metadata Extractor` and the `Advanced URI` plugin need to be installed in every vault you want to control, and`osetup` needs to be run once.)

Release will be in the Gallery in 1-2 days, or you can already directly download it here:
https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.8.0/shimmering-obsidian.alfredworkflow

**Comment by Sinled** [comment]
Excellent news, thank you!
