### ISSUE TITLE
Bug: Alfed Crash on `o`

### ISSUE THREAD

**Issue by bodtheone** [chrisgrieser/shimmering-obsidian#157]
### Bug Description

alfred crashes when typing o with workflow active, it happens only when typing o not even osetup

### Relevant Screenshot

i think its because it cant acces my vault in my pcloud alternative to google drive

### To Reproduce

get workflow and type the letter o in alfred command line

### Debugging Log

```Text
ERROR: Shimmering Obsidian[Script Filter] Code -1: Task '/Users/thomas/pCloud Drive/Thomas/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9F2A37DA-FFA6-48F1-95C9-67B55F4D245C/scripts/o_search.js' failed with reason 'launch path not accessible'
```

### Workflow Configuration

didnt change it

### Version & System Information

```Text
the newest now and alfred 5
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the documentation of the feature I am having problems with.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.

**Comment by chrisgrieser** [comment]
> Workflow Configuration
didnt change it

setting the vault path is required for the workflow to work:

![Pasted image 2023-10-27 at 08 21 48@2x](https://github.com/chrisgrieser/shimmering-obsidian/assets/73286100/5629449d-b1f3-45f1-903d-f4237dd5a47a)

If you have done that and still get a complete Alfred crash, I am afraid that's an issue with Alfred itself, and little I can do on my end. In this case, you'd have to report the bug on the Alfred forum, sorry.
