### ISSUE TITLE
Feature Request: Time Scheduled Backup

### ISSUE THREAD

**Issue by edoski** [chrisgrieser/shimmering-obsidian#159]
### Feature Requested

It would be neat if it was possible to have an option where you can set the vault to automatically backup (like via obackup) at a specified time interval.

Cheers, and once again great work on the wonderful workflow!

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hi & thx!

Timed backups are unfortunately not sth you can do via Alfred.  I'd look into automation apps like Keyboard Maestro for that.
