### ISSUE TITLE
Feature Request: Append to scratchpad with dynamic prefix (date and time)

### ISSUE THREAD

**Issue by obarlev** [chrisgrieser/shimmering-obsidian#160]
### Feature Requested

As it seems, the scratchpad prefix supports static strings only.
It would be very useful to add date and time as a prefix for instance 

- 03/12/2023 16:30:57 - some scratchpad text

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by jamie9090** [comment]
+1

**Comment by chrisgrieser** [comment]
The scratchpad actually already supports that feature: You can use [Alfred's Dynamic placeholders](https://www.alfredapp.com/help/workflows/advanced/placeholders/) to add things like a date, for example via `{date}`. 

Only thing is, that this feature is actually not documented anywhere 🙈 
I added some pointers in the readme and the workflow configuration to make it clearer that Alfred's placeholders are supported.

**Comment by jamie9090** [comment]
Only request for this, can we use the {query} command without having it double up? This way we can put the date at the end :)

**Comment by chrisgrieser** [comment]
That's not supported, and unfortunately also a bit too niche in my view. In think for your needs, creating your own custom workflow for adding to files would be a much better fit for your needs.
