### ISSUE TITLE
Where can I find release notes?

### ISSUE THREAD

**Issue by cmbail** [chrisgrieser/shimmering-obsidian#166]
### Feature Requested

I love that there have been so many releases since I first downloaded this a couple months ago https://github.com/chrisgrieser/shimmering-obsidian/releases

I may be missing something stupidly obvious, but I've looked around and can never find details of what features were added/bugs were fixed by each release. Are there release notes somewhere? If there are none because you're too busy, I'm happy to help write them!

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Yeah, there are many releases, but they are mostly very minor 😛 

There is a simple changelog inside Alfred, when you open the workflow configuration/workflow info.
