### ISSUE TITLE
Feature Request: Note preview

### ISSUE THREAD

**Issue by ctwhome** [chrisgrieser/shimmering-obsidian#167]
### Feature Requested

For a much more quicker access and look up for the correct note. It will allow you to quickly check a note without changing the context. Like the clipboard preview feature in Alfred.

Also will help to identify quickly the correct note to open in full in obsidian (if necessary)

PS: thanks for the hard work!

### Relevant Screenshot

<img width="764" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/4195550/a9cd8db2-3a5e-49b1-a425-b0b5d1a5d994">

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hi,

I very much would also like to have such a preview feature, unfortunately, Alfred does provide any such functionality that you could use. You would have to post at the Alfred Forum and request such a feature there: https://www.alfredforum.com/forum/5-alfred-feature-suggestions/

Post the link here, and I'll gladly upvote your request.
