### ISSUE TITLE
Feature Request: Allow running any Obsidian commands

### ISSUE THREAD

**Issue by YousufSSyed** [chrisgrieser/shimmering-obsidian#170]
### Feature Requested

I would like to completely replace Obsidian's ocmmand palette with Shimmering Obsidian, but I can enter in specific Obsidian commands with it. There should be a keyword to do so and as I type it shows me a list of commands that match the query I type.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Opening files is something that makes sense from outside of Obsidian, but I really see what the benefit of a command palette outside of Obsidian is.

I think that all in all, the feature is a bit too specific and not many people would use it, sorry.
