### ISSUE TITLE
Bug report/technical issue, folder browsing not working correctly due to output caching

### ISSUE THREAD

**Issue by Hekate1** [chrisgrieser/shimmering-obsidian#176]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

Not a feature request but no other options available. I am running into issues where folder browsing doesn't work correctly, nothing happens when a folder is selected. I have determined that the issue is the caching of the output of o_search.js. If the output is not cached (by removing the cache item at the end of o_search.js), folder browsing works (though this obviously slows things down in the cases that caching would be effective).

I am not sure whether there is something specific to my setup that causes the output caching to break things. Using version 4.7.1

### Alternatives considered

N/A

**Comment by chrisgrieser** [comment]
ah, wasn't aware that Alfred's caching mechanism had that effect. Thanks, fixed with latest release.
https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.7.2/shimmering-obsidian.alfredworkflow

**Comment by chrisgrieser** [comment]
bug report form had a bug, also fixed
