### ISSUE TITLE
Feature Request: Open Note in New Window

### ISSUE THREAD

**Issue by macrospecter** [chrisgrieser/shimmering-obsidian#179]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

This workflow is amazing; works reliably like a charm, and has so much functionality. But there's one modification that would make it close to perfect for me: if the open-in-new-tab option when creating a new note could be altered to instead open the new note in a new window (or if that function could be added as an additional option). I use new windows more often than new tabs, because the former clutter my current workspace less. I assume I'm not totally alone in this preference.

Indeed, I saw that someone else previously requested this feature. I could see in GitHub that one of the new commits referenced that request, but I couldn't tell how and, as far as I can understand, the feature wasn't implemented.

### Alternatives considered

I tried to do this by altering the new-note.js script to use a different URI command than "obsidian://advanced-uri?vault=${vaultNameEnc}&commandid=workspace%253Anew-tab," but every one I tried to use didn't quite work (including when I tried to use the URI command for certain Commander plugin macros). This may just be a feature of Obsidian's new/limited introduction of window manipulation, but I hope that there's a way to do this. 

I also saw that, with the helpful guide/workflow you created for triggering one's own Obsidian command, it is possible to create a new note in a new window. However, it would be helpful if one could create a new note as part of this same workflow, and choose to either create it in the same or a new tab (or, as requested here, in a new tab), as in the original design. It would also be great to have this function integrated into the "open [existing] note" function in the workflow.

**Comment by chrisgrieser** [comment]
Added in version 4.9.0. 

Will be available in 1-3 days via update from the Alfred Gallery, or you can already download it directly here: https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.9.0/shimmering-obsidian.alfredworkflow

**Comment by macrospecter** [comment]
Fabulous, thank you. Would it be possible to make the option apply also to the "Create New Note" feature, as well as the "Open Note" feature?

**Comment by chrisgrieser** [comment]
Wouldn't creating a simple workflow that creates a new note in a new window work? 

The workflow starts has so many settings as it is and I am kind of hesitant to add more settings, since it's gonna get harder to find settings then.  (And I wouldn't want to have the one setting apply to both, since many people would not want that)

**Comment by macrospecter** [comment]
No worries, I can see why you wouldn't want to bulk up the settings too much. I just thought it might be an easy thing to add for consistency's sake. The ability to at least open notes in a new window is invaluable, and I can just supplement with the separate workflow.

**Comment by chrisgrieser** [comment]
As opposed to using a new command, you would use the obsidian advanced uri plugin's uri for writing a new note: https://vinzent03.github.io/obsidian-advanced-uri/actions/writing

And where the new note is opened is determined by the opening mode parameter: https://vinzent03.github.io/obsidian-advanced-uri/concepts/navigation_parameters

**Comment by macrospecter** [comment]
Amazing, thank you.
