### ISSUE TITLE
Feature Request: Support opening plugin folder in Finder

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/shimmering-obsidian#18]
**Is your feature request related to a problem? Please describe.**
Currently there are a few options with the `op` command, e.g. opening the plugin configuration pane. Is it possible to open the plugin folder in Finder?

**Describe the solution you'd like**
Support opening the plugin folder in Finder.

**Comment by chrisgrieser** [comment]
easy enough, will be implemented in the next release. 👍

**Comment by chrisgrieser** [comment]
ok, not super simple actually, because all the "space" for the modifier keys is already used up 😅

Therefore, will probably will the part of the release after the next. However, you can use `oplugin` to open the plugin folder in general in the meantime.

**Comment by chrisgrieser** [comment]
Implemented in release 2.1 via the new [Settings Search](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Settings%20Search.md). :)

**Comment by wenlzhang** [comment]
Thanks for the update!

I tried to use `o,` but it gave me the following errors from the debug console:
```
[13:25:26.212] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[13:25:26.533] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[13:25:26.534] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/xx/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D29ABBD5-F375-4C89-B556-DF4C2B2E5309/scripts/setting-search.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
```

Then it directed me to `Search Google for 'o,'`.

**Comment by chrisgrieser** [comment]
Have you updated to the newest version of the Advanced URI Plugin (which is needed for this)?

Also what exactly led to the error – trying to open a plugin's local folder or using the `o,` search in general?

**Comment by wenlzhang** [comment]
I am using version 1.14.0 of the Advanced URI plugin. It should be the latest version.

Whenever I type `o,`, I see the error.

**Comment by chrisgrieser** [comment]
Are you developing a plugin of your own or are you using beta plugins (= not downloaded via the community store)?

**Comment by wenlzhang** [comment]
Yes, I am using beta plugins in a vault that Shimmering Obsidian is configured for. One is the Calendar plugin:
https://github.com/liamcain/obsidian-calendar-plugin/releases/tag/2.0.0-beta.2

Another one is not publicly available.

I have some other beta plugin in other vaults that Shimmering Obsidian are not configured for.

**Comment by chrisgrieser** [comment]
> I have some other beta plugin in other vaults that Shimmering Obsidian are not configured for.

**Comment by chrisgrieser** [comment]
Okay, found the issue, it's beta plugins where the developer hasn't released a file called `manifest.json` yet which is causing the trouble. Those files contain metadata for plugins that the settings search utilizes. 

It should be fixed in [hotfix-release 2.1.1](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/2.1.1).

(Only minor issue that the plugin's name cannot be properly displayed – the dev of the beta plugin where this is the case needs to add a `manifest.json` for it to work.)

**Comment by wenlzhang** [comment]
It seems that one cannot open the setting page of such a beta plugin? E.g. the calendar plugin I posted above.

**Comment by chrisgrieser** [comment]
yep, that's a restriction cause the beta plugin doesn't have all the necessary information needed for that yet.

**Comment by wenlzhang** [comment]
Okay then. Thanks for the clarification.
