### ISSUE TITLE
Feature Request: customize keyboard shortcut?

### ISSUE THREAD

**Issue by yimingli** [chrisgrieser/shimmering-obsidian#184]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#table-of-contents) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

My keyboard doesn't have a `fn` key? Would it be possible to customize keyboard shortcuts?

### Alternatives considered

I considered remapping some keys to a function key, but my keyboard is quite small, and there's no spare keys that I can map to `fn`.

**Comment by chrisgrieser** [comment]
Sorry, to my knowledge, it is not possible to change the modifiers in such a way in Alfred.

Your best bet is to use a keyboard remapping app such as Karabiner Elements, as to my knowledge it allows you to remap key combinations, like remapping ctrl+cmd to fn.
