### ISSUE TITLE
Feature Request: Display first line or tags as subtitle in workflow

### ISSUE THREAD

**Issue by mjknght** [chrisgrieser/shimmering-obsidian#195]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#table-of-contents) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

Currently, the subtitle for the quick switcher is the path – useful if you use folders; not quite so useful if your fault is not structured in that way. Personally, all my results just have `▸ /` in the subtitle. 🙂

I have previously used Alfred quick switchers with other apps (e.g. Bear) that showed instead the first line of the body of the note or alternatively the tags in the subtitle. For the many people who use a flat structure in their vault, this would be more useful information when jumping to a note.

Additionally, implementing this would actually extend Obsidian’s usefulness beyond the default feature set in the following way. One thing missing from Obsidian itself is a core “note preview” view, where you can see a list of note titles + the first line of text. This, again, is one thing people miss when coming in from Bear and other apps (unless they use Dataview). So adding this to the subtitle would give us functionality in the workflow that Obsidian does not currently offer.

Thanks for considering this!

### Alternatives considered

The alternative is that when you start to quick switch to a note, and then realise you'd like a little more context, you have to switch to the app and use the preview popover or the search function. Quite cumbersome by comparison to what adding this would make possible.

**Comment by chrisgrieser** [comment]
Makes sense – added in latest release.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.11.0/shimmering-obsidian.alfredworkflow

**Comment by mjknght** [comment]
This is great, and such a swift response too! Thank you. Forgive me for following this with another ask, but would it ever be possible to show the first line of body text in this field, in place of the tags? That’s what I meant when I said first line or tags above – but reading through a couple of other issues here, it sounds like that would require a kind of access to the notes that is not currently possible… Just another thought; but this is already very helpful indeed.

**Comment by chrisgrieser** [comment]
Yeah, unfortunately, that's not possible, since Alfred does not have have access to the same data as An obsidian plugin
