### ISSUE TITLE
Bug: Notes do not open on minimized window

### ISSUE THREAD

**Issue by AIProductivity** [chrisgrieser/shimmering-obsidian#197]
### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the documentation of the feature I am having problems with.
- [X] I am using Alfred 5. (Alfred 4 is not supported by this workflow anymore.)
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.

### Bug Description

I'm unable to use the search and open a file function when obsidian is minimized

### Relevant Screenshot

![2024-10-26@2x](https://github.com/user-attachments/assets/a2bc9022-5038-4dc1-9105-8ce679fd2b66)

### To Reproduce

Minimize obsidian and try to open a file with this setup

### Debugging Log

```Text
[11:09:57.477] STDERR: Shimmering Obsidian[Run Script] URI opened: obsidian://advanced-uri?vault=Melkweg&filepath=Clients%2FYemen%2FNana.md
[11:10:01.299] STDERR: Shimmering Obsidian[Run Script] URI opened: obsidian://advanced-uri?vault=Melkweg&filepath=Clients%2FUAE%2FUnikai.md
[11:10:08.368] STDERR: Shimmering Obsidian[Run Script] URI opened: obsidian://advanced-uri?vault=Melkweg&filepath=Clients%2FLibya%2FTiba%20Dairy.md
```

### Workflow Configuration

![2024-10-26@2x](https://github.com/user-attachments/assets/0258b05e-2319-4353-a733-f724659cd084)

### Are you using Alfred in Compatibility Mode?

- [ ] I am using Compatibility Mode.

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/abdullah/Documents/Obsidian/Melkweg
config folder: exists
Metadata JSONs: 4/4
metadata.json String Length: 190237
-------------------------------
METADATA EXTRACTOR CONFIG
{"writingFrequency":"30","writeFilesOnLaunch":true}
-------------------------------
WORKSPACE DATA
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 15.0.1
Alfred: 5.5.1
-------------------------------
INSTALLED VERSION
Obsidian: 1.7.4
This Workflow: 4.10.3
Advanced URI Plugin: 1.44.1
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.7.4 (Insider: 1.7.4)
This Workflow: 4.10.3
Advanced URI Plugin: 1.44.1
Metadata Extractor: 1.1.0
-------------------------------
```

**Comment by chrisgrieser** [comment]
Unfortunately, the problem appears to lie with Obsidian core not being able to handle URIs while Obsidian is minimized. If you try to open `obsidian://open?vault=Melkweg` for example, it will also fail.

I can only recommend opening a bug report at the [Obsidian forum](http://forum.obsidian.md), unfortunately there is nothing I can do on my end.

**Comment by AIProductivity** [comment]
That is very unfortunate, in the last version it was perfectly fine, it used to work in the last version. Thank you for your fast reply though.

**Comment by AIProductivity** [comment]
@chrisgrieser is there a possibility for you to include a shortcut at the end? Command +F for example can pull the obsidian form minimized to full. Just an idea.

**Comment by chrisgrieser** [comment]
I'd rather not, since such hacks tend to break something else in return. It would really be best for Obsidian to fix this itself.

You can also hide (cmd+h) instead of minimizing (cmd+m), in which case URIs do works.

**Comment by chrisgrieser** [comment]
I think [Obsidian 1.7.6](https://obsidian.md/changelog/2024-11-12-desktop-v1.7.6/) should have fixed the issue:
> Fixed regression where Obsidian URI left the target window minimized.

**Comment by AIProductivity** [comment]
Thank you Chris!

Van: Chris Grieser ***@***.***>
Datum: dinsdag, 12 november 2024 om 15:38
Aan: chrisgrieser/shimmering-obsidian ***@***.***>
CC: AIProductivity ***@***.***>, Author ***@***.***>
Onderwerp: Re: [chrisgrieser/shimmering-obsidian] Bug: Notes do not open on minimized window (Issue #197)

I think Obsidian 1.7.6<https://obsidian.md/changelog/2024-11-12-desktop-v1.7.6/> should have fixed the issue:

Fixed regression where Obsidian URI left the target window minimized.

**Comment by AIProductivity** [comment]
Thank you, ChtusThank you, Cris

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Chris Grieser ***@***.***>
Verzonden: Tuesday, November 12, 2024 3:38:45 PM
Aan: chrisgrieser/shimmering-obsidian ***@***.***>
CC: AIProductivity ***@***.***>; Author ***@***.***>
Onderwerp: Re: [chrisgrieser/shimmering-obsidian] Bug: Notes do not open on minimized window (Issue #197)


I think Obsidian 1.7.6<https://obsidian.md/changelog/2024-11-12-desktop-v1.7.6/> should have fixed the issue:

Fixed regression where Obsidian URI left the target window minimized.
