### ISSUE TITLE
Bug: Tag Search throws an error

### ISSUE THREAD

**Issue by mjknght** [chrisgrieser/shimmering-obsidian#198]
### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the documentation of the feature I am having problems with.
- [X] I am using Alfred 5.5 (lower versions are not supported).
- [X] I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
- [X] If the `o…` main search does not work, I made sure that I haven't changed any of the default settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still does not work.
- [X] If notes in general can be found, but recently created or renamed notes cannot, I used the `oupdate` command to manually update the metadata.

### Bug Description

When I use the tag search, initially I am presented with a list of tags. But when I select one I get the following:

```
[13:50:56.162] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/mark/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.509AB3A4-9833-424F-8A1C-BC80FA6596FC/scripts/search-files-with-tag.js: execution error: Error: Error: exception raised by object: *** +[NSString stringWithUTF8String:]: NULL cString (-2700)
```

I don't recall seeing this error before the update.

### To Reproduce

1. Use `ot` search.
2. Press enter key on one of the results to drill down.
3. Nothing happens – just a blank search field.

### Debugging Log

```Text
[13:50:56.162] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/mark/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.509AB3A4-9833-424F-8A1C-BC80FA6596FC/scripts/search-files-with-tag.js: execution error: Error: Error: exception raised by object: *** +[NSString stringWithUTF8String:]: NULL cString (-2700)
```

### Workflow Configuration

None.

### Are you using Alfred in Compatibility Mode?

- [ ] I am using Compatibility Mode.

### Version & System Information

```Text
-------------------------------
INTERNAL WORKFLOW CONFIGURATION
Vault Path: /Users/mark/Documents/Work/Notes
config folder: exists
Metadata JSONs: 4/4
metadata.json String Length: 54539919
-------------------------------
METADATA EXTRACTOR CONFIG
{"writingFrequency":"30","writeFilesOnLaunch":true}
-------------------------------
WORKSPACE DATA
'workspace' exists
'workspace.json' exists
-------------------------------
SYSTEM
macOS: 14.6.1
Alfred: 5.5.1
-------------------------------
INSTALLED VERSION
Obsidian: 1.7.4
This Workflow: 4.11.0
Advanced URI Plugin: 1.44.1
Metadata Extractor: 1.1.0
-------------------------------
LATEST VERSION
Obsidian: 1.7.4 (Insider: 1.7.4)
This Workflow: 4.11.0
Advanced URI Plugin: 1.44.1
Metadata Extractor: 1.1.0
-------------------------------
```

**Comment by chrisgrieser** [comment]
Fixed.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.11.1/shimmering-obsidian.alfredworkflow
