### ISSUE TITLE
Feature Request: Option to paste copied link to frontmost app

### ISSUE THREAD

**Issue by mjknght** [chrisgrieser/shimmering-obsidian#199]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#table-of-contents) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

Most of the time, when I invoke this workflow to copy a link, it's because I want to paste it straight into the window in which I am working. I understand that not everyone would want this, but I think it would have broad enough appeal to add the option to not just copy the Wiki or Markdown link but to paste it into the frontmost app. Taking the extra step of pasting over copying feels redundant when you're in that scenario – at least to me.

### Alternatives considered

The alternative is just to undertake the extra step of pasting.

**Comment by chrisgrieser** [comment]
Makes sense, added in the latest release.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.12.0/shimmering-obsidian.alfredworkflow
