### ISSUE TITLE
QLMarkdown has issues with Big Sur

### ISSUE THREAD

**Issue by seishonagon** [chrisgrieser/shimmering-obsidian#2]
Hi, if you're installing qlmarkdown for the first time on a machine, you may run into some issues with getting Big Sur to trust it. FWIW, my path to resolution was helped by this link: [big sur - macOS Big Sur - Set quick look provider for specific file types? - Ask Different](https://apple.stackexchange.com/questions/408762/macos-big-sur-set-quick-look-provider-for-specific-file-types). 
If you simply use the Alfred workflow as is (e.g. o _name of file_ and then press <shift>) then you'll simply get an error message or a blank window.
You first need to go to one fo your .md files, press space (to call quicklook) and then go through the autorisation in Systems Preference. 

That said, amazing workflow, it's EXACTLY what I was looking for - Thanks

**Comment by chrisgrieser** [comment]
> That said, amazing workflow, it's EXACTLY what I was looking for - Thanks

Thanks!

> Hi, if you're installing qlmarkdown for the first time on a machine, you may run into some issues with getting Big Sur to trust it. FWIW, my path to resolution was helped by this link: big sur - macOS Big Sur - Set quick look provider for specific file types? - Ask Different.

Weird, I am sure that I didn't have that issue when I installed qlmarkdown. Nevertheless thanks pointing this out, I'll add this to the troubleshooting section of the documentation.

Otherwise, as there is no real issue to be fixed, I'll close this issue, I guess :)
