### ISSUE TITLE
Feature Request: Semantic Search via existing pluging

### ISSUE THREAD

**Issue by jralduaveuthey** [chrisgrieser/shimmering-obsidian#200]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#table-of-contents) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

Implement also Semantic Search from the Alfred bar. E.g. using any of these existing plugins https://github.com/solderneer/obsidian-ai-tools , https://github.com/bbawj/obsidian-semantic-search

### Alternatives considered

There are plugins that do it but it would be great to do it directly within Alfred for speed

**Comment by chrisgrieser** [comment]
Being an Alfred plugin, *Shimmering Obsidian* does not have access to the same kind of APIs as Obsidian plugins do. Thus, such a feature is better suited for Obsidian plugins than an Alfred workflow, sorry.

**Comment by jralduaveuthey** [comment]
thanks for the quick reply!
isnt it possible to use part of the plugin functionality within the Alfred
bar? or pass the content of the bar to the plugin as input?
