### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by MartinYuan1995** [chrisgrieser/shimmering-obsidian#202]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#table-of-contents) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

Hi, Buddy. I'm sorry to bother you but when I use the o function to search my notes, the picture saved in the local area will not appear through the quick-look function on mac.
![image](https://github.com/user-attachments/assets/f7da3051-abf0-49aa-a6ef-0d9b8c25d26e)

### Alternatives considered

Important information needs to be saved in the local area. however, the same  plug-in can do that such as https://github.com/hauselin/obsidian-alfred

**Comment by chrisgrieser** [comment]
Unfortunately, there is nothing the workflow can do about it, since the quicklook functionality is controlled by macOS, not by Alfred. Alfred can only trigger QuickLook, how the quicklook looks is out of Alfred's control. And `![[]]` is wikilink syntax specific to Obsidian, so I unfortunately doubt that there is any quicklook plugin that can change this, sorry.

**Comment by MartinYuan1995** [comment]
Thanks for your reply. but there is another plugin can solve this problem using oss function. (https://github.com/hauselin/obsidian-alfred). so it's very strange, but i have tested many times.

**Comment by chrisgrieser** [comment]
> using oss function.

please be more specific and provide screenshots, otherwise I cannot help. What does the plugin do, and how does it display quicklook functionality?

**Comment by MartinYuan1995** [comment]
Well, thank you. I'm not at the computer right now. When I go back, I will immediately record the screen.

**Comment by MartinYuan1995** [comment]
Hi, Thanks for your waiting.  You are right that there is no Quicklook plugin that can do this.

> Unfortunately, there is nothing the workflow can do about it, since the quicklook functionality is controlled by macOS, not by Alfred. Alfred can only trigger QuickLook, how the quicklook looks is out of Alfred's control. And `![[]]` is wikilink syntax specific to Obsidian, so I unfortunately doubt that there is any quicklook plugin that can change this, sorry.
