### ISSUE TITLE
FR: A command to search for notes and attachments at the same time

### ISSUE THREAD

**Issue by kennguyen107** [chrisgrieser/shimmering-obsidian#203]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#table-of-contents) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

I want to preface this by saying that the features technically already exist: Search Notes and Search Attachments. What I want is basically a command that does both at the same time (e.g. input "Math 131", then the command will search for all markdown files AND attachments (e.g. pdf files) that has "Math 131" in it).

Specifically, my use case is that I'm a college students and I'm using Obsidian to take notes. However, I only really take notes in markdown files in classes where the prof doesn't give lecture slides to the students. In the classes that do, I simply stored the slides as pdf inside obsidian.

Currently, I'd have to remember if class of the note I want to search for has lecture slides or not before deciding with whether I should do a "Search Note" or "Search Attachment". There are also some classes where some days have slides, but other days the prof just write on the board, so the result is that the same class can have both markdown files and pdf files at the same time. Therefore, it'd be very useful to have a command that can search for both of them within Obsidian at the same time.

That said, I'm not the one who develop this wonderful workflow, so I cannot speak to how complicated this will be or how much the speed/performance of the search will suffer by incorporating both of those features into one.

### Alternatives considered

The alternative is that I can simply use "Search Note" first, and if the note I want doesn't show up, then try "Search Attachment", which honestly isn't a big deal at all. This feature request isn't crucial and is simply a qol improvement. Please feel free to close this feature request if this feature turns out to be too complicated to implement or too slow to be useful!

**Comment by chrisgrieser** [comment]
Thanks for detailed request! While I can see your problem, I think that it is unfortunately a bit too niche to add to the workflow. 

For your particular use case, you might want to consider using an Obsidian plugin like `Another quick switcher`, which lets you create custom searches. Among other things, it is able to cover your scenario, and it's in my view better suited for the task than using Alfred.

**Comment by kennguyen107** [comment]
Thanks for your response! Also, I was reading through the README to understand how to use the workflow, and I noticed that the part about "Smart Queries" were duplicated. It isn't a bug with the workflow so I thought it wasn't worth opening a new issue.

**Comment by chrisgrieser** [comment]
> and I noticed that the part about "Smart Queries" were duplicated

Ah, looks like a copypaste mistake. Thanks for pointing it out, just fixed it!
