### ISSUE TITLE
[BUG] "Filepath/OCR-Screenshot.md not found"

### ISSUE THREAD

**Issue by kenanmike** [chrisgrieser/shimmering-obsidian#21]
Trying this workflow for this first time:
-Everything seems to have been installed properly, and when I perform the OCR screenshot the log in Alfred shows no issue (the text has been read fine and the action triggered in Obsidian)
-However, in Obsidian I get the following error message:
![image](https://user-images.githubusercontent.com/85374001/140473396-fce8f829-207a-475d-a7d0-b2b6bc8bfb91.png)
-I have tried manually creating a note called 'OCR-Screenshot' in my root Obsidian folder but it still gives the same error message. In the developer tools, the log says:
"VM194:27 Error requesting synonyms for word OCR-Screenshot TypeError: (intermediate value).first is not a function
    at Ft.eval (eval at <anonymous> (app.js:1), <anonymous>:27:60043)
    at Generator.next (<anonymous>)
    at o (eval at <anonymous> (app.js:1), <anonymous>:6:729)"

I'm on workflow v 2.0.2, MacOS Big Sur, Macbook Air (2018) intel.

**Comment by chrisgrieser** [comment]
found the problem, fixed in release 2.1 :)

**Comment by kenanmike** [comment]
Lightning quick and working now. Thanks so much Chris!
