### ISSUE TITLE
Feature Request: Daily Note Improvements

### ISSUE THREAD

**Issue by rapatel0** [chrisgrieser/shimmering-obsidian#22]
**Is your feature request related to a problem? Please describe.**

Currently the daily note requires absolute referencing but the advanced URI functionality allows for daily note based querying. I have a macro that sets up a daily note folder. This means that the daily note path changes per day: `/path-to-daily-note-folder/YYYY-MM-DD/YYYY-MM-DD.md`

**Describe the solution you'd like**
I've manually changed the `od` command to handle this but i think that it should be the default functionality 
![image](https://user-images.githubusercontent.com/18704704/140656158-ade2922a-5df7-43ed-a51c-869356e8df89.png)

This URI will open the daily note regardless of the path.
```
obsidian://advanced-uri?&daily=true
```

Advanced URI also allows specification of the vault incase there is a more flexibility that is required. Currently, the above command will default to the currently open vallt

**Comment by heliostatic** [comment]
Ah, I have the same issue with a different folder structure (`/path-to-daily-note-folder/YYYY/MM/YYYY-MM-DD.md`), and I didn't know about the Advanced URI solution -- that's great. Making this the default model, or more easily configured, would be great. Thanks!

**Comment by heliostatic** [comment]
Particularly trick to solve the append to daily note workflow, as well.

**Comment by chrisgrieser** [comment]
Shouldn't be too hard, I'll look into it when I continue working on this workflow!

**Comment by chrisgrieser** [comment]
As daily notes are by far the Number 1 request, I'll tackle a comprehensive daily note implementation for version 3.0. I am pinning this to avoid duplicate issues. :)

**Comment by chrisgrieser** [comment]
I am sorry to say that I feel a bit uneasy to work on and maintain the daily note feature – since I personally do not use daily notes myself, I would have to rely on someone else to maintain this, which probably isn't worth the effort. However, the [Alfred workflow by hauselin](https://github.com/hauselin/obsidian-alfred) does focus a lot more on daily note features, and can be used alongside this workflow without any issue. 

Therefore, I think it makes more sense to make a feature request for that hauselin's workflow.

**Comment by chrisgrieser** [comment]
well, as I said, I don't use daily notes, and therefore have neither interest nor competence to implement such a feature (considering all special cases there are, with date formats, weekly notes etc.)

I'd be open if anyone wants to contribute and maintain a daily note feature for this plugin, though.
