### ISSUE TITLE
Feature Request: content prefix when appending to daily notes

### ISSUE THREAD

**Issue by n3bulous** [chrisgrieser/shimmering-obsidian#24]
In order to improve the structure and rendering of my daily notes, I've added local support for a daily note leader. Result:

![CleanShot 2021-11-19 at 14 59 44](https://user-images.githubusercontent.com/5499/142696947-9823d9e7-d218-46cf-92f0-e7c462b1b0ac.png)

I've added a local variable `daily_content_prefix` which I set to `- {time:short} - `.

I add this variable at the beginning of the text area in the Append to File object: `{var:daily_content_prefix}{var:content}`

Thoughts on adding this or similar to the official distro?

**Comment by chrisgrieser** [comment]
yeah, since it seems daily notes improvements is right now the number one request (see also #22), this will probably be one of the things I tackle next. :)

**Comment by wenlzhang** [comment]
Is there any update on this?

For instance, I may use the following format for appending text to daily notes: `- {date:HH:mm} {var:content} 📝 {date:yyyy-MM-dd}T{date:HH:mm}`. Therefore, it would be great if one can add both prefix and suffix to the input text.

**Comment by chrisgrieser** [comment]
added in release 2.18 👍
