### ISSUE TITLE
[BUG] Browsing links doesn't work (reliably)

### ISSUE THREAD

**Issue by phlind** [chrisgrieser/shimmering-obsidian#25]
**Describe the Bug**
Using the show links feature (`ol`) does not show links of a note reliably. Sometimes it shows all links, sometimes it shows just one, but very often none at all. When I use `Shift` on a note searched by `o` it very often says "Note without outgoging links or backlinks", even though the note has links.

I looked at the extracted metadata file `metadata.json` and all the info about links seems to be there.

Running `oupdate` didn't solve the problem.

I don't know how to reproduce that issue and couldn't find any pattern in the notes that don't work.

**Debugging Log**

An example log from a note with two outgoing and two incoming links, showing no links in Alfred:

```
[12:15:13.082] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[12:15:13.805] Shimmering Obsidian[Keyword] Processing complete
[12:15:13.807] Shimmering Obsidian[Keyword] Passing output '' to Run Script
[12:15:14.256] Shimmering Obsidian[Run Script] Processing complete
[12:15:14.263] Shimmering Obsidian[Run Script] Passing output 'Maps of Content.md' to Replace
[12:15:14.264] Shimmering Obsidian[Replace] Processing complete
[12:15:14.266] Shimmering Obsidian[Replace] Passing output 'Maps of Content.md' to Call External Trigger
[12:15:14.267] Shimmering Obsidian[External] Processing complete
[12:15:14.268] Shimmering Obsidian[External] Passing output 'Maps of Content.md' to Arg and Vars
[12:15:14.269] Shimmering Obsidian[Arg and Vars] Processing complete
[12:15:14.270] Shimmering Obsidian[Arg and Vars] Passing output ' ' to Script Filter
[12:15:14.290] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[12:15:14.518] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[12:15:14.525] Shimmering Obsidian[Script Filter] {"items":[]}
```

**Checklist**
- [x] I have updated to the latest version of this workflow, the Advanced URI plugin, and the Metadata Extractor plugin.
- [x] I have read and checked the [Troubleshooting](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).

**Comment by chrisgrieser** [comment]
Hmm, I tested the feature and it all works for me. The debugging log also doesn't show anything out of the ordinary (except not displaying items at the end). That means, we will need to to create a "Test Vault" to reproduce the issue.

Could you create a new vault, copy the notes in question (and their linked notes, of course) into that vault, and install the advanced URI and metadata extractor plugin in that vault in there? Afterwards, you must tell Alfred to control that vault via the vault switcher: `ov` and select the vault with `shift + return`.

Now you can try the `ol` command and see whether the issue still occurs. if the issue doesn't occur at all, try adding chunks of your original vault into it and test whether the `ol` command still works.

I know this is takes a bit of time, but without any type of hint what condition causes the note to be found and which not, I don't know an easier way of finding the issue 😕

**Comment by joelcostajr** [comment]
Exact same issue here. I thought it might have to do with wikilinks vs. md but I converted my internal links and still didn't work. All outgoing web links are found by the workflow, but the internal links are not. (BTW, thank you for creating this awesome tool!)

**Comment by chrisgrieser** [comment]
Since I cannot reproduce the issue, I can only take a guess. I fixed something which *might* have been the cause of some issues. So please update to version 2.9.8 and try again whether Browsing links works now.

If it doesn't help, I really need some sort of test vault where I can reproduce the issue, [as mentioned before](https://github.com/chrisgrieser/shimmering-obsidian/issues/25#issuecomment-979981573).

**Comment by chrisgrieser** [comment]
Okay, I have found and fixed a bug for the link-browsing via `shift + return` and the `ol` which *sometimes* causes it to fail. Could you check whether it works now? (version 2.9.12)

**Comment by chrisgrieser** [comment]
Since there are also no further reports, I assume that this is fixed. please re-open if there are still problems
