### ISSUE TITLE
Feature Request:  preset a specific note to which to manually append text

### ISSUE THREAD

**Issue by posedonius** [chrisgrieser/shimmering-obsidian#28]
for input_append = manual:

- specify a predetermined note to which to manually append text.  maybe specify this note in "workflow environment variables" (or anywhere else).  
- ideally we launch alfred and simply type "x this_is_text_to_append_to_preset_note".  meaning, type only one letter, instead of two letters, followed by text to append to that note we already preset.

**Comment by chrisgrieser** [comment]
implemented in release 2.15.0 as the scratchpad feature
https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Note-related%20Features.md#scratchpad
