### ISSUE TITLE
Feature Request: option to append to beginning of file, instead of only at end

### ISSUE THREAD

**Issue by posedonius** [chrisgrieser/shimmering-obsidian#29]
for input_append = manual:

- option to append to beginning of file, instead of only at end.

**Comment by chrisgrieser** [comment]
closing this is issue since stale

**Comment by aljustiet** [comment]
> for input_append = manual:
> 
> * option to append to beginning of file, instead of only at end.

How do I add the note to the beginning of the file instead of the end of the file?
