### ISSUE TITLE
Feature Request: move blocks from current note to a preset "archive" note

### ISSUE THREAD

**Issue by posedonius** [chrisgrieser/shimmering-obsidian#31]
for example, to move completed tasks from current note, to an archive note:

- preset an archive note
- move selected blocks from one note to the beginning or end (optional) of that archive note
- an alfred command to automate this for done tasks, scan current note for all done tasks, move them all to the archive note. or specify another attribute to scan for, like a certain tag in that block
- the obsidian42 text transporter plugin does something similar, but there is no preset note option there.

thanks

**Comment by chrisgrieser** [comment]
Hmm, I'm not sure about this feature. More fine-grained interaction with note contents isn't really something for which Alfred is well-suited due to being a third-party app. To me, it rather looks like a Feature Request for the Obsidian42 Text Transporter plugin? 🤔

**Comment by posedonius** [comment]
true, i get carried away with my enthusiasm for alfred.

**Comment by chrisgrieser** [comment]
> true, i get carried away with my enthusiasm for alfred.
As a developer of a bunch of Alfred workflows, I can totally understand :)

Also, will tackle your FR in the next couple of weeks, at the latest during Christmas break when I got some more time.
