### ISSUE TITLE
broken link in documentation:  browse links...

### ISSUE THREAD

**Issue by posedonius** [chrisgrieser/shimmering-obsidian#32]
in the shimmering alfred workflow documentation, there seems to be a broken link here:

-   `⇧ + ↵`: Browse a list of all links of the selected note (outgoing links, backlinks, external links.) See at the [section "Browse Links" below](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Alfred-based%20Quick%20Switcher.md#Browse-Links-of-**_the-Current_**-Note) for further information.

maybe replace "the-Current" with "a" ?

otherwise the documentation is clear and beautifully laid out.

**Comment by chrisgrieser** [comment]
thanks, that's a link I forgot to update when changing the heading. Was exactly what you mentioned, I have fixed it.
