### ISSUE TITLE
QLMarkdown doesn't preview notes (yet it works fine for .md notes in finder)

### ISSUE THREAD

**Issue by seishonagon** [chrisgrieser/shimmering-obsidian#34]
**Describe the Bug**
I've installed QLMarkdown and it seems to work properly when invoked from the Finder:

<img width="400" alt="Screenshot 2021-12-05 at 07 17 12" src="https://user-images.githubusercontent.com/6635078/144736128-32c4ff05-56df-4de5-80d0-15c12968a489.png">

Yet when I try to access the SAME NOTE using Shimmering Obsidian, I get the generic "can't preview" image:

<img width="400" alt="Screenshot 2021-12-05 at 07 17 36" src="https://user-images.githubusercontent.com/6635078/144736164-1b445144-b9ab-42b0-83cf-c80ed67fec2e.png">

I've also checked that QL works well with Alfred in other ways. Here's a quick look at THE SAME FILE but found via the quote operator:
<img width="400" alt="Screenshot 2021-12-05 at 07 33 46" src="https://user-images.githubusercontent.com/6635078/144736380-386b8c52-7f9a-4787-9ba8-e4930f84f88c.png">
and generally the QL function works well every where and for every type of files.

**To Reproduce**
It's systematic on my machine. 

**Relevant Screenshots**
(see above)

**Debugging Log**
[debug shimmering.txt](https://github.com/chrisgrieser/shimmering-obsidian/files/7655340/debug.shimmering.txt)

```
logdata
```

**Checklist**
- [x] I have updated to the latest version of this workflow, the Advanced URI plugin, and the Metadata Extractor plugin.
- [x] I have read and checked the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [x] I read the [Breaking Changes Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Breaking%20Changes.md) to make sure the unexpected behavior is not a breaking change.

**Comment by chrisgrieser** [comment]
Thanks for the thorough report, that saved quite a bit of time narrowing it down!

I found the issue, and it is fixed in version 2.9
