### ISSUE TITLE
General note search (o "note name") not showing any results

### ISSUE THREAD

**Issue by melancond1** [chrisgrieser/shimmering-obsidian#35]
I typically use just "o" in Alfred to pull up a specific note that I'm looking for, and as of today it is not providing me with any results

**Comment by chrisgrieser** [comment]
After updating to 2.9, you need to run the `osetup` command once! 
<img width="515" alt="Screenshot 2021-12-06 23 15 52" src="https://user-images.githubusercontent.com/73286100/144931545-2bb028ea-444d-4094-b5d5-9304edd4032d.png">

**Comment by melancond1** [comment]
I'm having trouble with finding the vault that I use in the setup this time, is there a way to add specific vaults to the setup process?

**Comment by chrisgrieser** [comment]
could you elaborate what kind of trouble you have?

**Comment by melancond1** [comment]
![18A2393A-FF97-41F8-BD78-F7EFFE24686D](https://user-images.githubusercontent.com/84878594/144933872-aa96d638-7e6f-4f3e-9c01-22527eb5c5eb.jpeg)
This is what shows up when I go to run the setup process

However, after using that setup process, I still just see the following in my search results despite being on the note I'm looking for:
![67A0A710-548C-4EBA-9DCA-981AFF2EE20A](https://user-images.githubusercontent.com/84878594/144933981-295517ae-304a-46be-a338-ff51e308a07e.jpeg)

My vault is named "Main Brain" and does not show up in the setup process. It is, however, located in "Obsidian" in the overarching folder. Is there somewhere in Alfred's preferences that I should go to help it find the pathing to the correct vault?

**Comment by melancond1** [comment]
An additional note is I have the pathname in Alfred set to where it should be:
![162C4345-FBD7-4EFA-80F1-91DC57C1887A](https://user-images.githubusercontent.com/84878594/144935449-f29db823-126c-4648-9095-da76c6dbd2fb.jpeg)

**Comment by chrisgrieser** [comment]
the `o` search only works when you have installed the two plugins (Advanced URI and Metadata extractor) in the selected vault. I assume you have only installed them in "Main Brain", which you could not select, therefore northing is showing up. 

And the path name does not suffice with the newest version.

---

Could you confirm that all four of your vaults do show up in the vault menu in the list to the left?
<img width="797" alt="Screenshot 2021-12-06 23 49 22" src="https://user-images.githubusercontent.com/73286100/144935322-75c3c445-48ee-4bdb-9177-1d78041b2f05.png">

If all four vaults do show up, could go to the folder `~/Library/Application Support/obsidian/` and copy the content of the file `obsidian.json`?

**Comment by melancond1** [comment]
Is the Metadata extractor a new requirement? That was the problem actually, I reran the setup with it and it's working now. Thank you for your help!

**Comment by chrisgrieser** [comment]
Did "Main Brain" show up when you ran `osetup` again?

Yeah, the metadata extractor is a "new" requirement [since version 2.0](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Breaking%20Changes.md#version-20) which I published a few weeks ago :P

There if you just only now updated from 1.x to 2.x, please check out the docs, since a lot of stuff has changed.

**Comment by melancond1** [comment]
It does show up now! Thank you again for the help, I definitely will! I normally try to read new documentation, but I'm admittedly in finals weeks and research deadlines and it got pushed back very far on my to-do list 😅

**Comment by chrisgrieser** [comment]
well, good luck with your finals then!

closing this, since this is solved I guess.
