### ISSUE TITLE
Refine documentation on dependencies

### ISSUE THREAD

**Issue by nwehrle** [chrisgrieser/shimmering-obsidian#4]
Could you add some sentences or bulletpoints to the paragraphs **Required Third-Party Software** and **Required Obsidian Plugins** on why this very dependency is needed. Some people want to keep their installation lean.

Name | what does the dep do | why is it needed in shimmering-obsidian
------|------|------
qlmarkdown | quickview filter | ?
hotkey helper | configurable shortcuts in O | ?
... | ... | ...

Nice addition to the documentation would be also, that qlmarkdown needs to be added to "System-Settings/Privacy/General" first. https://github.com/toland/qlmarkdown/issues/98#issuecomment-607733093

**Comment by nwehrle** [comment]
Found the hint to qlmarkdown in the Troubleshooting section 🙈

**Comment by chrisgrieser** [comment]
Thanks for the suggestion! [I made the respective changes to the Requirements section](https://github.com/chrisgrieser/shimmering-obsidian#requirements--installation).
