### ISSUE TITLE
Feature Request: configuration options to make 'on' more capable

### ISSUE THREAD

**Issue by 00dani** [chrisgrieser/shimmering-obsidian#42]
**Feature Requested**
Currently if you're not using QuickAdd, then new notes created using the `on` command always end up in the root of your vault. I'd like my new notes to end up in my Inbox folder, which can easily be done by editing the workflow myself but can't be done through configuration. I don't think this is an uncommon desire, although "Inbox" isn't always the name of the appropriate subfolder.

If you *are* using QuickAdd, then you can certainly configure QuickAdd itself to create new notes in particular folders - *however*, it looks like you can't specify the title of your new note when you call `on` with QuickAdd enabled. The parameter to `on` seems to be treated as the particular QuickAdd choice to activate, so you'd write something like `on capture to inbox` rather than `on remember the milk`.

Ideally, I think `on` should let you direct notes to a subfolder if you're not using QuickAdd - and if you *are*, perhaps there should be an option to pre-specify which QuickAdd choice you want to use? Then you could configure up front that you always want to use "capture to inbox", and then you could type `on remember the milk`, which makes more sense to me.

**Checklist**
- [x] The feature would be useful to more users than just me.
- [x] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [x] If it is an entirely new feature and not just a feature improvement: The requested feature makes more sense to be implemented in Alfred than in a plugin. (It's specifically about the behaviour of Shimmering Obsidian's `on` command, so it doesn't make a lot of sense to do it outside of the workflow itself.)

**Comment by chrisgrieser** [comment]
version 2.17 lets you specific a location for new notes.

I personally prefer to have access to different QuickAdd options. To quickly open a specific QuickAdd option, you can easily create a super-simple workflow of your own: 
https://forum.obsidian.md/t/alfred-workflow-for-obsidian/23297/7
https://forum.obsidian.md/t/alfred-workflow-for-obsidian/23297/9
