### ISSUE TITLE
[BUG] OCR error:  make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory

### ISSUE THREAD

**Issue by posedonius** [chrisgrieser/shimmering-obsidian#43]
hello, when i ocr, i get the following error message appended into the "ocr-screenshot" note above the successfully ocr'd text.  is there a way to address this so that only the ocr'd text below appears?  thanks, and happy holidays.
_______

Error opening data file /opt/homebrew/share/tessdata/deu.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'deu'

**Comment by chrisgrieser** [comment]
Hi, it seems you have `deu` set as language, but haven't installed the necessary package for it.

You either have to install it via `brew install tesseract-lang`, or you need to set the workflow configuration `ocr_languages` to `eng` only
