### ISSUE TITLE
[BUG] Getting `JSON Parse error` when running `o ...` command

### ISSUE THREAD

**Issue by ericbiewener** [chrisgrieser/shimmering-obsidian#44]
**Describe the Bug**
Same initial error as [this issue](https://github.com/chrisgrieser/shimmering-obsidian/issues/20), but it has never worked for me since I just installed this workflow today.

`o ...` command not working

**To Reproduce**
1. Install metadata extractor
1. Install this workflow
1. run `oupdate`
1. try running `o ...`

I have confirmed that the following files exist in `<vault>/.obsidian/plugins/metadata-extractor`:

```text
data.json
main.js
manifest.json
```

**Debugging Log**
```text
[12:16:51.997] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[12:16:52.220] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[12:16:52.221] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/ericbiewener/Drive/App Settings/Alfred.alfredpreferences/workflows/user.workflow.1B2C8640-B18E-461B-AB4D-CA73E3590924/scripts/o_search.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
```

**Version Information**
```text
_
-------------------------------
Metadata JSONs: 0/3
Metadata not found. Please run `osetup` and retry.
-------------------------------
INSTALLED VERSION
macOS: 11.6
Obsidian: 
Alfred: 4.6.1
Workflow: 2.12.3
Advanced URI Extractor: 1.16.1
Metadata Extractor: 0.2.4
-------------------------------
LATEST VERSION
Obsidian: 0.13.14
Obsidian (Insider): 0.13.18
Workflow: 2.12.3
Advanced URI Extractor: 1.16.1
Metadata Extractor: 0.2.4
-------------------------------
```

**Checklist**
- [x] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [x] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).

**Comment by chrisgrieser** [comment]
> data.json
main.js
manifest.json

however, those are the are not the files needed, you need these three files in the directory. And you debugging log says they are not. Those are the three needed:

```text
metadata.json
allExceptMd.json
tags.json
``` 

> 3. run `oupdate`
You need to run `osetup` though, not `oupdate`. That changed a few versions ago; have I missed changing that in the docs somewhere?

**Comment by ericbiewener** [comment]
I have run `osetup` as well and get the success notification & automatic Obisidian restart. But I still don't see those files listed in `.obsidian/plugins/metadata-extractor` -- or should they be in a different location?

I ran `oupdate` based on a suggestion in [this comment](https://github.com/chrisgrieser/shimmering-obsidian/issues/20#issuecomment-961874129), but now I see I misread it and really needed to run `Manually Refresh Metadata`. But I have done that as well and still see no change in the `metadata-extractor` plugin directory, and I get the same debug error.

**Comment by chrisgrieser** [comment]
that means the files are somehow not written correctly by the metadata extractor.

could you make a screenshot of the metadata extractor plugin settings?

also, open the Alfred debugging log, then run `osetup` or `oupdate` ➞ `Manually Refresh metadata`. And post what the debugging log says when it's trying to write the metadata.

**Comment by ericbiewener** [comment]
Ah, I'm sorry @chrisgrieser, the metadata extractor plugin was disabled. I'm an Obsidian noob and keep forgetting that after installing plugins they start out as disabled. Everything is working fine now. Sorry for wasting your time!

**Comment by chrisgrieser** [comment]
no worries! Obsidian is a lot to take in, and my Alfred workflow certainly also has some extensive docs. 😅 🙂
