### ISSUE TITLE
Feature Request: Support appending suffix to content

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/shimmering-obsidian#46]
### Feature Requested

Besides prefix, as suggested in https://github.com/chrisgrieser/shimmering-obsidian/issues/30 and https://github.com/chrisgrieser/shimmering-obsidian/issues/24, it would also be very useful if one can append suffix to the text, i.e. `{var:daily_content_prefix}{var:content}{var:daily_content_suffix}` and `{var:append_prefix}{query}{var:append_suffix}`.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
closing this is issue since stale
