### ISSUE TITLE
[Bug]: o keyword in Alfred not giving option to search Obsidian

### ISSUE THREAD

**Issue by shawnduggan** [chrisgrieser/shimmering-obsidian#47]
### Bug Description

When I trigger Alfred and type o, followed by a space and my search term, only the default search options are available.

I do see the option to search Obsidian flash by, but it is replaced by all the default search options. Using a different keyword, like oos doesn't change what happens.

I have run the setup, and the od command works to open my daily note. So I think the workflow is installed and mostly configured.

Is this a configuration issue with Alfred? Any advice is appreciated. 

### Relevant Screenshot

<img width="717" alt="Screen Shot 2022-01-22 at 12 04 05 PM" src="https://user-images.githubusercontent.com/3504807/150646263-bcf341b6-179a-4a26-a901-59e9481834ad.png">

<img width="723" alt="Screen Shot 2022-01-22 at 11 58 23 AM" src="https://user-images.githubusercontent.com/3504807/150646076-4447964e-91ec-4ac1-9374-570a6c78893f.png">

### To Reproduce

1. Trigger Alfred
2. Type o followed by a space then a search term

### Debugging Log

[12:00:53.791] Logging Started...
[12:01:00.416] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[12:01:00.727] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[12:01:00.730] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/shawn/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AAABE307-D7C7-4EEA-92C5-7E71386A21EB/scripts/o_search.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)

### Version Information

v2.18

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o ...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
please provide the information you have skipped (version information, debugging log, screenshot, etc.) – they are there for a reason. I cannot help you without them. ("only default search options" could mean anything, depending on how you set Alfred up)

**Comment by shawnduggan** [comment]
I have added the requested information. Thanks for getting back to me.

**Comment by chrisgrieser** [comment]
Could you post a screenshot of your Alfred workflow environment variables?

+ run `oversions` and paste the result here?

**Comment by shawnduggan** [comment]
-------------------------------
Metadata JSONs: 1/3
Metadata not found. Please run `osetup` and retry.
-------------------------------
INSTALLED VERSION
macOS: 12.1
Obsidian: 0.13.21
Alfred: 4.6.1
Workflow: 2.18.0
Advanced URI Plugin: 1.17.0
Metadata Extractor: 0.2.4
-------------------------------
LATEST VERSION
Obsidian: 0.13.19
Obsidian (Insider): 0.13.21
Workflow: 2.18.1
Advanced URI Plugin: 1.17.0
Metadata Extractor: 0.2.4
-------------------------------
<img width="990" alt="Screen Shot 2022-01-22 at 12 43 05 PM" src="https://user-images.githubusercontent.com/3504807/150647757-9aff2045-3c70-47e5-becc-af9b4b57b199.png">
<img width="995" alt="Screen Shot 2022-01-22 at 12 43 19 PM" src="https://user-images.githubusercontent.com/3504807/150647765-221e1ac8-7c1f-4c37-a32c-5a2fbde63a9c.png">

**Comment by chrisgrieser** [comment]
> Metadata JSONs: 1/3
Metadata not found. 

Yeah, there seems to be some issue with the metadata writing, for whatever reason. Could you run `oupdate` ➞ `Manually Refresh Metadata` and try again?

**Comment by shawnduggan** [comment]
That fixed it! Thank you. Great workflow - thank you for sharing it.

**Comment by chrisgrieser** [comment]
Thanks 😊
