### ISSUE TITLE
[Bug]: [SOLVED] Screenshot file always created at root of vault

### ISSUE THREAD

**Issue by seishonagon** [chrisgrieser/shimmering-obsidian#50]
### Bug Description

Whatever value the screenshot path variable {var: screenshot_path} takes, the screenshot OCR files OCR_screenshot.md is always generated at the root of the vault.

Turns out the path description in the workflow omits the variable altogether(see screenshot)

The path in the append to file action is: 
{var:vault_path}/OCR-Screenshot.md

It should be:
{var:vault_path}/{var:screenshot_path}/OCR-Screenshot.md

### To Reproduce

Create a screenshot and check it out. 

### Debugging Log

Not necessary, the fix is in the bug description

### Workflow Configuration

not necessary, one variable is affected

### Version & System Information

```text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.1
Obsidian: 0.13.21
Alfred: 4.6.1
Workflow: 2.18.6
Advanced URI Plugin: 1.17.0
Metadata Extractor: 0.2.4
-------------------------------
LATEST VERSION
Obsidian: 0.13.19
Obsidian (Insider): 0.13.21
Workflow: 2.18.6
Advanced URI Plugin: 1.17.0
Metadata Extractor: 0.3.1
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o ...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
actually not a bug, the setting `screenshot_path` was simply only meant for image screenshot :P

I have added a separate setting to set the target file for OCR to release 2.19.0 though
