### ISSUE TITLE
Open Daily Note taking precedence over Append to Daily Note?

### ISSUE THREAD

**Issue by adamwolf** [chrisgrieser/shimmering-obsidian#58]
This is great stuff!  I just got it set up.  Everything I've tried seems to work great, except `od`.  When I open Alfred and type `od hello world`, I see two results:

* Open Today's note 
* Append to Today's Daily note
 
The top one is selected.  If I hit enter, it opens my note, but my text seems to be gone.  If I press down and then enter, it seems to append.

I went into the workflow, clicked on the od entry for opening, and changed it to No Arguments.

Now, it seems to work like I expect.  If I type `od`, it shows just Open Today's note, and then if I keep typing, it only shows Append to...

Is there something messed up with my setup, do you think?  Am I supposed to have to hit down in order to append with `od foo`?

**Comment by chrisgrieser** [comment]
good idea, changed it to your suggestion.
