### ISSUE TITLE
Feature Request: Trigger metadata extraction

### ISSUE THREAD

**Issue by caalberts** [chrisgrieser/shimmering-obsidian#64]
### Feature Requested

I would like to be able to trigger a metadata extraction from Alfred directly.

Metadata extractor is configured to extract periodically or at every startup. Sometimes, we want to quickly interact with a new note from Alfred, but the note has not been processed by metadata extractor yet. The current workaround is to restart obsidian, but that requires additional context switching to Obsidian.

An alternative to this is to implement new trigger into metadata extractor to extract each time a note is created. However, I'm not sure about the performance impact of this. Having it on demand via Alfred seems like the next best alternative.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
That's already possible with `oupdate` :)

**Comment by caalberts** [comment]
@chrisgrieser thanks for pointing that out. Now I see it in https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Utility%20Features.md#update-plugins--metadata.

Would you think a dedicated command such as `orefresh` would make it more discoverable? FWIW, `oupdate` does not show option to refresh metadata until it is fully typed.

<img width="562" alt="Screenshot 2022-03-08 at 6 22 15 PM" src="https://user-images.githubusercontent.com/4749355/157217273-4780effb-03bd-4518-9cc3-d00a616b0010.png">

<img width="560" alt="Screenshot 2022-03-08 at 6 22 20 PM" src="https://user-images.githubusercontent.com/4749355/157217282-09c14877-b850-427c-967e-cdb439742e35.png">

**Comment by chrisgrieser** [comment]
> Would you think a dedicated command such as orefresh would make it more discoverable? 

I thought about it, but since the vast majority of users will not refresh this manually, I refrain from adding even more commands to the workflow (it's a lot as it is). You can also simply trigger the refreshing via hotkey , since it's the Metadata-Extractor plugin you are running, which might be the better solution for you anyway.

> FWIW, oupdate does not show option to refresh metadata until it is fully typed.

that is intentional to prevent cluttering things up.

**Comment by caalberts** [comment]
Sounds good to me. Thanks for responding.
