### ISSUE TITLE
[Bug]: Unable to append to daily note

### ISSUE THREAD

**Issue by caalberts** [chrisgrieser/shimmering-obsidian#65]
### Bug Description

I tried to use `od` to append to daily note, but it could not append to the note. In the debug log, I see a line "You can't save the file ...".

Initially I thought it was a file permission problem for the directory, however, the `oo` command to append to scratchpad works fine. Since they both write to file, there should not be any issue with permissions.

### Debugging Log

```Text
[11:06:19.493] Shimmering Obsidian[[Arg and Vars](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.722B3955-9F7C-4F5D-B384-DD708495B4C2%3E06632743-0C08-41BC-B058-146CDF2C11F8)] Passing output '2022-03-08' to [Write Text File](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.722B3955-9F7C-4F5D-B384-DD708495B4C2%3ED28DF759-C300-4F54-A228-97AC41E07C27)
[11:06:19.494] ERROR: Shimmering Obsidian[[Write Text File](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.722B3955-9F7C-4F5D-B384-DD708495B4C2%3ED28DF759-C300-4F54-A228-97AC41E07C27)] You can’t save the file “2022-03-08.md” because the volume “Macintosh HD” is read only.
```

### Workflow Configuration

<img width="484" alt="Screenshot 2022-03-08 at 11 23 44 AM" src="https://user-images.githubusercontent.com/4749355/157160160-b295755c-dd25-4890-a689-af4632f85b50.png">

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.2
Obsidian: 0.13.30
Alfred: 4.6.3
Workflow: 2.21.7
Advanced URI Plugin: 1.20.0
Metadata Extractor: 1.0.0
-------------------------------
LATEST VERSION
Obsidian: 0.13.30
Obsidian (Insider): 0.13.30
Workflow: 2.21.7
Advanced URI Plugin: 1.20.0
Metadata Extractor: 1.0.0
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
sorry for the late reply – the error occurs because you have not [set a path to your daily notes folder in your workflow configuration](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Workflow%20Configuration.md#note-related-features)
<img width="484" alt="157160160-b295755c-dd25-4890-a689-af4632f85b50" src="https://user-images.githubusercontent.com/73286100/158270493-af9ade26-3a1f-480d-9e95-97967feecd4a.png">
.
