### ISSUE TITLE
[Bug]: External link title not parsed correctly

### ISSUE THREAD

**Issue by teake** [chrisgrieser/shimmering-obsidian#67]
### Bug Description

The [regex that parses the external links](https://github.com/chrisgrieser/shimmering-obsidian/blob/c748c9e7599aead24f0bd9d483f128027293dcad/scripts/browse-note-links.js#L81) a little bit too greedy. In e.g. checkbox lists such as

```
- [ ] Some text [A description 1](https://example.com/link1/).
```

it matches `[ ] Some text [A description 1](https://example.com/link1/)`. See https://regexr.com/6iaju. The title of the external link then becomes ` Some text [A description 1`.

Setting the regex to `\[[^\]]*\]\([^\)]+\)` fixes this, see https://regexr.com/6iak7.

### Debugging Log

```Text
N/A.
```

### Workflow Configuration

N/A.

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.3
Obsidian: 0.13.33
Alfred: 4.6.4
Workflow: 2.21.9
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.0
-------------------------------
LATEST VERSION
Obsidian: 0.13.33
Obsidian (Insider): 0.14.2
Workflow: 2.21.9
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.0
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
thanks, fixed in the latest release

**Comment by teake** [comment]
That was fast. Thanks!
