### ISSUE TITLE
[Bug]: `om`(Move Note function) cannot  work

### ISSUE THREAD

**Issue by Miaoyifei-mz** [chrisgrieser/shimmering-obsidian#72]
### Bug Description

In version 2.22.3 or 2.22.2 , `om` function (Move the current note to a different folder in your vault) cannot work. The list of folders in Obsidian does not appear in Alfred's window.

**But in 2.22.1, `om` function can work.**🤔

### Relevant Screenshot

**In version 2.22.3 or 2.22.2**

<img width="676" alt="image" src="https://user-images.githubusercontent.com/60280844/163983422-52c34694-27f9-4391-9ad6-f888ee4845f4.png">

**In version 2.22.1**

<img width="676" alt="image" src="https://user-images.githubusercontent.com/60280844/163983504-7f49e464-4424-409f-a39c-59616819b5b9.png">

### To Reproduce

Happens every time.

### Debugging Log

```Text
[18:23:28.033] Logging Started...
[18:23:32.631] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[18:23:37.252] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[18:23:37.400] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[18:23:37.402] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/zhuangzhu/Nutstore Files/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EF132D1B-640E-430C-85D6-A0403847E8C3/scripts/search-folders.js: execution error: Error: Error: exception raised by object: *** +[NSString stringWithUTF8String:]: NULL cString (-2700)
```
```


### Workflow Configuration

<img width="522" alt="image" src="https://user-images.githubusercontent.com/60280844/163983857-3886286e-0369-4609-8be5-ba5b2bf12376.png">


### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.3.1
Obsidian: 0.14.6
Alfred: 4.6.4
Workflow: 2.22.3
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.1
-------------------------------
LATEST VERSION
Obsidian: 0.14.6
Obsidian (Insider): 0.14.6
Workflow: 2.22.3
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.1
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
oh, that one is actually a mistake by me, since I meant to completely remove that feature 🙈 

Problem is that moving files via Alfred does not preserve their wikilinks, so that I kept on using Obsidian's internal feature for it. There is no way to do this reliably within Alfred, and the feature also has little benefit since you can do it with plugins as well, so I decided to remove it.

I properly removed the feature from the workflow and the docs in the most recent update – thanks for pointing out that I forgot about that.
