### ISSUE TITLE
[Docs]: Add examples for Windows PC

### ISSUE THREAD

**Issue by ManasMadrecha** [chrisgrieser/shimmering-obsidian#76]
### Change Requested

Currently, the examples of how to install, which all hotkeys to use, etc. are specific to Mac. It would be great if corresponding Windows examples are added as well in all the README files. 

### Link to the relevant section of the documentation

https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Screenshot%20Features.md#ocr-screenshots

**Comment by chrisgrieser** [comment]
But Alfred is a Mac only app, so you cannot use the workflow on Windows...?
