### ISSUE TITLE
[Docs]: Need to add info regarding metadata refresh rate to the documentation

### ISSUE THREAD

**Issue by OleksandrYuvkoExt** [chrisgrieser/shimmering-obsidian#77]
### Change Requested

Hi there, I wasn't fully aware about inner processes of plugin and how it actually work. The problem that I had was: when I add new tag, or whatever I can't find it and have to re-start obsidian. After some investigation I have found that shimmering-obsidian searches not through files but through extracted metadata by utilising kometenstaub/metadata-extractor. And metadata-extractor is refreshing metadata with default delay of 30 minutes(it can be configured), or after killing and launching Obsidian.

So it will be nice to have a brief description of shimmering-obsidian inner work on main page. And DEFINITELY documentation should have a description how to configure re-extraction delay.

Thank you!

### Link to the relevant section of the documentation

https://github.com/chrisgrieser/shimmering-obsidian

**Comment by chrisgrieser** [comment]
The fact that the plugin uses the Metadata from the Metadata extractor plugin is mentioned [here, together with two methods on how to change the frequency](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Workflow%20Configuration.md#metadata-extractor-plugin-configuration). It is [also mentioned here in the Trouble-shooting section](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md#alfred-based-quick-switcher-o--search-).

Do you have any suggestion where else to add the information?

**Comment by OleksandrYuvkoExt** [comment]
I mean initially it's just my problem, cause everything was in documentation, and it's an open source. Just trying to help newcomer's that are equally stupid as me 😄
