### ISSUE TITLE
Obsidian notes searching problem

### ISSUE THREAD

**Issue by redsox1283** [chrisgrieser/shimmering-obsidian#81]
### Change Requested

The workflow for searching notes on my laptop run perfectly well. However, when I adopt the same condition to my another laptop, somehow I can't use search function at all. Any suggestion?

### Link to the relevant section of the documentation

https://github.com/chrisgrieser/shimmering-obsidian

**Comment by chrisgrieser** [comment]
Have you installed all pre-requirements (metadata extractor, advanced uri) and run `osetup` on the other device as well?

If so, please open a bug report, since the form includes various kinds of information I need for debugging 🙂

**Comment by redsox1283** [comment]
The problem are solved since I upgrade the Mac (the one can't not use search function) from Mojave to Catalina. So is there a limitation for this workflow on older version of MacOS? And if I still need to open a bug report?

**Comment by chrisgrieser** [comment]
Hmm, weird. But glad it works for you. 

No, no need to open a bug report then the workflow not working on older versions is gonna solve itself over time, so 🙈
