### ISSUE TITLE
[Bug]: Problem with searching notes (o-search)

### ISSUE THREAD

**Issue by shunnkou** [chrisgrieser/shimmering-obsidian#82]
### Bug Description

When typing in "`o`", nothing shows up. Other types of searches (`ot`, `os`, `or`) and commands (`ob`, `oc`, `ol`) works though. The fallback search doesn't work either.

I have run `osetup` and `oupdate` multiple times, and I only have 1 vault. Both `Metadata Extractor` and the `Advanced URI` plugins, are installed, enabled, and up-to-date.

Thank you for your time.

### Debugging Log

```Text
[18:39:50.217] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[18:39:50.360] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[18:39:50.360] ERROR: Shimmering Obsidian[Script Filter] Code 1: undefined
/Users/name/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D780A9DC-2D75-4E19-931D-46F26F4C6998/scripts/o_search.js: execution error: Error: TypeError: undefined is not an object (evaluating 'excludeFilter.length') (-2700)
```

### Workflow Configuration

<img width="735" alt="image" src="https://user-images.githubusercontent.com/50721364/172073636-0f73e204-1890-42d6-a663-f4e394ba3dc9.png">

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.4
Alfred: 4.6.6

Obsidian: 0.14.15
This Workflow: 2.24.0
Advanced URI Plugin: 1.22.0
Metadata Extractor: 1.0.1
-------------------------------
LATEST VERSION
Obsidian: 0.14.6 (Insider: 0.14.15)
This Workflow: 2.24.0
Advanced URI Plugin: 1.22.0
Metadata Extractor: 1.0.1
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
thanks, fixed in release 2.24.1
