### ISSUE TITLE
2.42.3 introduces bug for "append to today's Daily Note"

### ISSUE THREAD

**Issue by derekvan** [chrisgrieser/shimmering-obsidian#83]
I think the fix introduced a bug unfortunately. When I try to append something to the daily note via "od" it appends it to a note called "{yyyy-mm-dd}" (literally--it doesn't populate the variables). I rolled back to 2.42.2 and instituted my fix above.

_Originally posted by @derekvan in https://github.com/chrisgrieser/shimmering-obsidian/issues/79#issuecomment-1171798352_

**Comment by joshsarvesh** [comment]
same bug here. Is there a fix ? I rolled back to 2.22.2 but still no fix.

**Comment by chrisgrieser** [comment]
should be fixed in latest release
