### ISSUE TITLE
[Bug]: Plugin can't search in notes after seemingly successful install

### ISSUE THREAD

**Issue by scorchio** [chrisgrieser/shimmering-obsidian#85]
### Bug Description

I've installed the necessary dependencies and completed `osetup` which restarted Obsidian, but after that, the notes did not come up when typing `o <something>` into Alfred.

Please note that I'm running Alfred and Obsidian on a fairly out-of-date macOS, which might explain the issue.

(BTW, the doc referred in "I have read the Troubleshooting documentation" points to a wrong link - https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md gives a 404 for me. It should be docs instead of documentation.)

### Debugging Log

```Text
[21:12:24.584] Logging Started...
[21:12:28.006] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[21:12:28.115] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[21:12:28.116] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/scor/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.718E5CD1-C8A3-4F7D-A50B-BEF3C0D7EAF0/scripts/o_search.js:2600:2628: script error: Error on line 82: SyntaxError: Unexpected token '.' (-2700)
```

### Workflow Configuration

![Képernyőfotó 2022-07-09 - 21 15 54](https://user-images.githubusercontent.com/236650/178119740-8f388b30-1bab-4728-bbea-1e03138dd488.png)

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 10.14.6
Alfred: 4.6.7

Obsidian: 
This Workflow: 2.26.7
Advanced URI Plugin: 1.23.0
Metadata Extractor: 1.0.1
-------------------------------
LATEST VERSION
Obsidian: 0.14.15 (Insider: 0.15.5)
This Workflow: 2.26.7
Advanced URI Plugin: 1.23.0
Metadata Extractor: 1.0.1
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
> (BTW, the doc referred in "I have read the Troubleshooting documentation" points to a wrong link - https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md gives a 404 for me. It should be docs instead of documentation.)

oh thx, fixed.

---

I am not entirely sure what causes this bug (though it shouldn't be the OS version). I have made a change that potentially fixes the issue. Could you update to 2.26.8 and try again? If it still does not work, could you attach the debugging log from trying the o-search again?

**Comment by chrisgrieser** [comment]
This should be fixed with the latest release (version 3, requiring Alfred 5). If not, please re-open!
