### ISSUE TITLE
[Docs]: OCR Language Settings

### ISSUE THREAD

**Issue by slyfoxgh** [chrisgrieser/shimmering-obsidian#86]
### Change Requested

Can you please update the OCR language settings? I can't figure out how to add another language. Do I use a "," or ";" or new line?

Edit: Found that I had to use eng+rus

Please add "+" into documentation 

### Link to the relevant section of the documentation

https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Screenshot%20Features.md

**Comment by chrisgrieser** [comment]
thanks! added to the docs.
