### ISSUE TITLE
[Bug]: `ol` is one page behind

### ISSUE THREAD

**Issue by bramses** [chrisgrieser/shimmering-obsidian#88]
### Bug Description

Hi! Amazing work on Shimmering, I'm wildly impressed :)

`ol` seems to be one note behind. Say I'm on `File A` and I run `ol`. But if I then open `File B` and run `ol` I get the links from `File A`.

I think it might have to do with active path not updating in `.obsidian` but I'm not sure.

```
function readFile (path, encoding) {
		if (!encoding) encoding = $.NSUTF8StringEncoding;
		const fm = $.NSFileManager.defaultManager;
		const data = fm.contentsAtPath(path);
		const str = $.NSString.alloc.initWithDataEncoding(data, encoding);
		return ObjC.unwrap(str);
	}

	const vaultPath = $.getenv("vault_path").replace(/^~/, app.pathTo("home folder"));
	const activeFile = JSON.parse(readFile(vaultPath + "/.obsidian/workspace"))
		.lastOpenFiles[0];

	return activeFile;
```

### Relevant Screenshot

I'm currently on this page (as in, its open in Obsidian, being edited) but `ol` is looking at the last page (debugging log below)
<img width="676" alt="Screenshot 2022-07-16 20-46-07" src="https://user-images.githubusercontent.com/3282661/179380563-aeed640e-27ac-4556-bb25-94c1159614e3.png">

### Debugging Log

```Text
{"items":[{"title":"⬅️ 🕑 2022-W29","match":"recent  2022 W29 2022-W29 ","subtitle":"▸ Weekly","type":"file:skipcheck","quicklookurl"...
```

### Workflow Configuration

<img width="650" alt="Screenshot 2022-07-16 20-47-36" src="https://user-images.githubusercontent.com/3282661/179380583-f7df0f1f-6ee0-48a6-a80a-228d301b2ea3.png">

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
Metadata String Length: 4948599
-------------------------------
INSTALLED VERSION
macOS: 12.4
Alfred: 4.6.4

Obsidian: 0.15.6
This Workflow: 2.26.8
Advanced URI Plugin: 1.23.0
Metadata Extractor: 1.0.2
-------------------------------
LATEST VERSION
Obsidian: 0.15.6 (Insider: 0.15.6)
This Workflow: 2.26.8
Advanced URI Plugin: 1.23.0
Metadata Extractor: 1.0.2
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
yeah, it seems with the newer Obsidian versions, the workspace file only contains the *last* files opened, not the current file. I switched the method of retrieving the active file in the latest release, this should work now.
