### ISSUE TITLE
[Bug]: Cannot open Today's note

### ISSUE THREAD

**Issue by Missionary2112** [chrisgrieser/shimmering-obsidian#90]
### Bug Description

I typed in Alfred the keyword to open Today's note in Obsidian. But it cannot find the vault. Everything else works fine.

### Relevant Screenshot

![Screenshot - 2022-07-21 22 35 46 (CleanShot)](https://user-images.githubusercontent.com/98799613/180370160-a69362dd-4827-44e0-89cf-ee2067d6f30d.jpg)

### To Reproduce

Type the keyword in Alfred to open Today's note in Obsidian.

### Debugging Log

```Text
[22:38:20.333] Shimmering Obsidian[Keyword] Processing complete
[22:38:20.334] Shimmering Obsidian[Keyword] Passing output '' to Arg and Vars
[22:38:20.335] Shimmering Obsidian[Arg and Vars] Processing complete
[22:38:20.336] Shimmering Obsidian[Arg and Vars] Passing output '2022-07-21' to Open URL
[22:38:20.362] Shimmering Obsidian[Open URL] Processing complete
[22:38:20.363] Shimmering Obsidian[Open URL] Passing output '(
    "obsidian:///Users/missionary/Library/Mobile%2520Documents/iCloud~md~obsidian/Documents/Missionary/%F0%9F%97%93%2520Calendar/2022-07-21.md"
)' to Call External Trigger
[22:38:20.364] Shimmering Obsidian[External] Processing complete
[22:38:20.365] Shimmering Obsidian[External] Passing output '(
    "obsidian:///Users/missionary/Library/Mobile%2520Documents/iCloud~md~obsidian/Documents/Missionary/%F0%9F%97%93%2520Calendar/2022-07-21.md"
)' to Conditional
```

### Workflow Configuration

![Screenshot - 2022-07-21 22 39 29 (CleanShot)](https://user-images.githubusercontent.com/98799613/180370608-24e0423b-c74a-41ab-a9ae-1ba4708a5c90.jpg)

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.4
Alfred: 5.0

Obsidian: 0.15.7
This Workflow: 2.26.4
Advanced URI Plugin: 1.24.0
Metadata Extractor: 1.0.2
-------------------------------
LATEST VERSION
Obsidian: 0.15.6 (Insider: 0.15.7)
This Workflow: 2.26.8
Advanced URI Plugin: 1.24.0
Metadata Extractor: 1.0.2
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by kurko** [comment]
Same here. After `osetup`, it tries to open the Daily Note file without specifying what Vault to use.

<img width="623" alt="Screen Shot 2022-08-02 at 15 42 17" src="https://user-images.githubusercontent.com/70312/182449818-c249e005-8954-474a-84b1-edf7e6056182.png">

<img width="372" alt="Screen Shot 2022-08-02 at 15 42 22" src="https://user-images.githubusercontent.com/70312/182449783-1b2616b1-6ef1-42dd-8c43-acf19989007d.png">

**Comment by Miaoyifei-mz** [comment]
Same issue.

**Comment by TimS-ml** [comment]
Same issue, change od URL to "obsidian://open?vault={var:valut_name_ENC}&file={var:daily_note_path}/{query}.md" works for me

**Comment by TimS-ml** [comment]
> 

And change od append to daily note {query}.md to "open?vault={var:valut_name_ENC}&file={var:daily_note_path}/{query}.md"

**Comment by Miaoyifei-mz** [comment]
Just like this? `obsidian://open?vault={Md%20%E6%96%87%E6%A1%A3}&file={3-%E6%97%A5%E8%AE%B0%2F}/{query}.md` 

But it doesn't work for me. @TimS-ml

**Comment by Miaoyifei-mz** [comment]
I change obsidian URL in 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/60280844/184787065-b674422f-9489-4f0d-a56a-2a0bee377d69.png">

**Comment by chrisgrieser** [comment]
Hi everyone, sorry for the late response, had to work on other repos I maintain.

Since I do not use daily notes myself and cannot properly maintain the feature, I unfortunately have to remove the daily notes functionality (it has been deprecated for a while now). I simply don't find the time maintaining features that I do not use myself, but are time-intensive to work on. Especially since I am the sole maintainer of multiple repos.

I encourage you to check out the [Alfred workflow for Obsidian by hauselin](https://github.com/hauselin/obsidian-alfred), which focuses on daily notes and complements this workflow well.

**Comment by chrisgrieser** [comment]
As a sidenote, I fixed an issue caused by users migrating their Alfred 4 workflow settings, in case you did:
<img width="614" alt="Pasted image 2022-09-14 13 38 13" src="https://user-images.githubusercontent.com/73286100/190143905-a9cda178-09b3-4060-b7e1-31f0b07e7d03.png">

**Comment by eliliam** [comment]
> I encourage you to check out the [Alfred workflow for Obsidian by hauselin](https://github.com/hauselin/obsidian-alfred), which focuses on daily notes and complements this workflow well.

@chrisgrieser I was hoping to find support for daily notes over at the extension you referenced, however it appears that repo hasn't had any updates in over three years and according to recent issues in the repo, it looks like there are some problems with working with daily notes in that workflow. I'm wondering if you're aware of any other workflows out there that are still maintained which support daily notes as this is a hugely useful feature to many. 

I understand it is not one that you use, and thus does not make sense to implement it, but I do feel that if there was at least a basic level of functionality that could be added to Shimmering Obsidian, even something as basic as opening the most recently created file in a given folder(which is how most people have daily notes configured, with a dedicated folder for the daily notes which new notes are created in as days go by), it would open the door to many people who are relying on the now unmaintained [obsidian-alfred](https://github.com/hauselin/obsidian-alfred) workflow.
