### ISSUE TITLE
Feature Request: Custom Icons

### ISSUE THREAD

**Issue by nilfric** [chrisgrieser/shimmering-obsidian#91]
### Feature Requested

Thanks for this great workflow!

It would be great if the user could customize the icons used for the the script results, like for notes, headings, links etc.

### Checklist

- [X] Feature Requests regarding daily notes unfortunately will not be implemented, since I do not use daily notes myself and there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
Hi! You can already do that quite easily, by replacing the respective png files in this folder.
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/73286100/187093895-79614487-cfe3-4644-9016-1970e9325f81.png">

However, every time an update for the workflow is released, this will get reset, so make a backup. 

To be persistent, I'd have to add settings for icon customization, which, tbh aren't that high of a priority for me, unfortunately.

That being said, if you want to design a nicer icon set, I'd be open to replace the current icon set with it.

**Comment by nilfric** [comment]
Thanks for the hint. I should have mentioned that I already did that, sorry. As you wrote, the issue is with having to do it whenever the workflow updates.

Unfortunately I'm no designer 😞
