### ISSUE TITLE
[FR]: Allow a profile location other than `.obsidian`

### ISSUE THREAD

**Issue by solidgonk** [chrisgrieser/shimmering-obsidian#92]
### Change Requested

When using custom profiles in obsidian, e.g. ('.obsidian-macos'), the workflow setup will not be able to find the plugins, even if you have them installed. 
The workaround is to open to revert back to the default profile ('.obsidian') and install them there, then switch back to your regular profile. 
This workaround will be problematic, as the plugins in the default profile will not be updated in line with your regular profile, so a variable would be best in the long term.

### Link to the relevant section of the documentation

https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Workflow%20Configuration.md

**Comment by chrisgrieser** [comment]
I will be occupied with rewriting my theme for 0.16 for a bit, but this is a good point, I haven't thought of that.

(anyone feel free to make a PR to the documentation, the variable will be a bit tricker since the path is hardcoded at *a lot* of places 🙈)

**Comment by chrisgrieser** [comment]
yeah, thing is, I haven't thought of people using custom config directories, and it's hardcoded in *a lot* of places, in different languages (applescript, js, shell, alfred vars etc.), which makes it simply a time-consuming task of modifying it everywhere.

I simply haven't gotten around to do it yet. but yeah, the named workaround (or simply renaming the config folder back) is probably the easiest way for now 😅

**Comment by chrisgrieser** [comment]
okay, with the great refactor for version 4.0, this has been implemented as well
<img width="447" alt="Pasted image 2023-08-11 at 10 01 33@2x" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/73286100/f5c70e62-99a0-4283-a8d7-90b37d9a3a28">
