### ISSUE TITLE
How do I choose a line break as the scratchpad_append_prefix

### ISSUE THREAD

**Issue by kenanmike** [chrisgrieser/shimmering-obsidian#94]
Hello! 

Instead of any other prefix, I just want a simple line break so that there's some white space between each item that's gone to the scratchpad. How can I do that?

Thanks again for this amazing workflow! I use it daily 😃

**Comment by chrisgrieser** [comment]
Thanks!

You can ahead so that. Even though it's not very apparent,`scratchpad_append_prefix` (Alfred variables in general) does accept multi-line content. Type a line break in your text editor, and copy paste it into `scratchpad_append_prefix`, will already work! 🙂

**Comment by kenanmike** [comment]
Amazing! Just tried it and it worked. Very cool.
Thanks again so much 🙏
