### ISSUE TITLE
[Bug]: Workflow crashes due to missing supercharged_icon_file variable 

### ISSUE THREAD

**Issue by hy1o** [chrisgrieser/shimmering-obsidian#96]
### Bug Description

I installed the workflow and ran osetup.
The workflow crashes and I turned on the debug mode.

```
/Users/xxx/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9272AAEE-A18D-4800-AB9F-BB138436EFB1/scripts/recent_searcher.js: execution error: Error: Error: exception raised by object: *** +[NSString stringWithUTF8String:]: NULL cString (-2700)
```

It was happening with almost every workflow command.
Further debugging reveals that it was trying to get supercharged_icon_file variable from the environment that doesn't exist.

I added supercharged_icon_file with a random value in info.plist and it resolved the issue.
I am wondering if this is a bug or if I missed a step during setup.

### To Reproduce

1. Install the workflow
2. Run osetup
3. Try any command (ot, or, ...)

### Debugging Log

```Text
/Users/xxx/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9272AAEE-A18D-4800-AB9F-BB138436EFB1/scripts/recent_searcher.js: execution error: Error: Error: exception raised by object: *** +[NSString stringWithUTF8String:]: NULL cString (-2700)
```
```


### Workflow Configuration

Couldn't find prefs.plist

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
Metadata String Length: 244012
-------------------------------
INSTALLED VERSION
macOS: 12.5
Alfred: 4.6.2

Obsidian: 0.15.9
This Workflow: 3.0.0
Advanced URI Plugin: 1.24.0
Metadata Extractor: 1.0.2
-------------------------------
LATEST VERSION
Obsidian: 0.15.9 (Insider: 0.16.2)
This Workflow: q
Advanced URI Plugin: 1.26.1
Metadata Extractor: 1.0.2
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.
- [X] If I updated from version 2.27.x to 2.28+, I have properly checked out the new information in the workflow configuration and also tried restarting Alfred.

**Comment by chrisgrieser** [comment]
Hi, most likely this is due to you using version 3 of this workflow, which requires Alfred 5. 

You either need to upgrade to Alfred 5, in which case you should also re-install the workflow once and *not* migrate your old settings from Alfred 4.

Or you need downgrade the [latest release still compatible with Alfred 4](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/2.27.7).
